"use client";

import { FileDown } from "lucide-react";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

interface ExportProps {
  storeName: string;
  dateRange: string;
  metrics: {
    totalRevenue: number;
    revenueGrowth: number;
    totalOrders: number;
    totalVisits: number;
    conversionRate: string;
    uniqueCustomers: number;
    averageOrderValue: number;
    abandonmentRate: string;
    retentionRate: string;
    inStockProducts: number;
  };
  topProducts: { name: string; salesCount: number; price: number; image?: string }[];
  recentOrders: { customerName: string; totalAmount: number; status: string; createdAt: string }[];
  lowStockProducts: { name: string; stock_quantity: number }[];
}

const SECTION_COLORS = {
  header: [10, 12, 20] as [number, number, number],
  section: [26, 29, 45] as [number, number, number],
  row: [15, 17, 26] as [number, number, number],
  cyan: [6, 182, 212] as [number, number, number],
  purple: [168, 85, 247] as [number, number, number],
  pink: [236, 72, 153] as [number, number, number],
  red: [239, 68, 68] as [number, number, number],
};

function drawHeader(doc: jsPDF, storeName: string, pageWidth: number, dateRange: string) {
  doc.setFillColor(...SECTION_COLORS.header);
  doc.rect(0, 0, pageWidth, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text(storeName, 20, 28);
  doc.setFontSize(10);
  doc.setTextColor(...SECTION_COLORS.cyan);
  doc.text("Analytics Report", pageWidth - 20, 28, { align: "right" });

  doc.setTextColor(100, 116, 139);
  doc.setFontSize(9);
  doc.text(`Period: ${dateRange}`, 20, 50);

  doc.setDrawColor(...SECTION_COLORS.cyan);
  doc.setLineWidth(0.5);
  doc.line(20, 64, pageWidth - 20, 64);
}

function drawFooter(doc: jsPDF, pageWidth: number) {
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFillColor(...SECTION_COLORS.header);
  doc.rect(0, pageHeight - 15, pageWidth, 15, "F");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Generated by Shopora Analytics • ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    pageHeight - 6,
    { align: "center" }
  );
}

function drawSectionTitle(doc: jsPDF, title: string, y: number, pageWidth: number, color?: [number, number, number]) {
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.setFillColor(...(color || SECTION_COLORS.section));
  doc.rect(20, y, pageWidth - 40, 8, "F");
  doc.text(title, 24, y + 6);
}

export default function ExportButton(props: ExportProps) {
  const exportPDF = () => {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const { metrics, topProducts, recentOrders, lowStockProducts, storeName, dateRange } = props;
    const pageWidth = doc.internal.pageSize.getWidth();

    drawHeader(doc, storeName, pageWidth, dateRange);

    let y = 72;
    drawSectionTitle(doc, "Key Metrics", y, pageWidth);
    y += 16;
    autoTable(doc, {
      startY: y,
      head: [["Metric", "Value", "Detail"]],
      body: [
        ["Revenue", `$${metrics.totalRevenue.toFixed(0)}`, `Growth: ${metrics.revenueGrowth.toFixed(1)}%`],
        ["Orders", `${metrics.totalOrders}`, `Avg Value: $${metrics.averageOrderValue.toFixed(0)}`],
        ["Visits", `${metrics.totalVisits}`, `Conversion: ${metrics.conversionRate}%`],
        ["Customers", `${metrics.uniqueCustomers}`, `Retention: ${metrics.retentionRate}%`],
        ["Abandonment", `${metrics.abandonmentRate}%`, `In Stock: ${metrics.inStockProducts}`],
      ],
      theme: "grid",
      headStyles: { fillColor: SECTION_COLORS.cyan, textColor: [0, 0, 0], fontStyle: "bold", fontSize: 9 },
      bodyStyles: { fillColor: SECTION_COLORS.section, textColor: [255, 255, 255], fontSize: 9 },
      alternateRowStyles: { fillColor: SECTION_COLORS.row },
      margin: { left: 20, right: 20 },
    });

    y = (doc as any).lastAutoTable.finalY + 14;

    if (topProducts.length > 0) {
      drawSectionTitle(doc, "Top Products", y, pageWidth);
      y += 16;
      autoTable(doc, {
        startY: y,
        head: [["Rank", "Product", "Sales", "Revenue"]],
        body: topProducts.map((p, i) => [`#${i + 1}`, p.name, `${p.salesCount} sold`, `$${(p.salesCount * p.price).toFixed(0)}`]),
        theme: "grid",
        headStyles: { fillColor: SECTION_COLORS.purple, textColor: [0, 0, 0], fontStyle: "bold", fontSize: 9 },
        bodyStyles: { fillColor: SECTION_COLORS.section, textColor: [255, 255, 255], fontSize: 9 },
        alternateRowStyles: { fillColor: SECTION_COLORS.row },
        margin: { left: 20, right: 20 },
      });
      y = (doc as any).lastAutoTable.finalY + 14;
    }

    if (recentOrders.length > 0) {
      drawSectionTitle(doc, "Recent Orders", y, pageWidth);
      y += 16;
      autoTable(doc, {
        startY: y,
        head: [["Customer", "Amount", "Status", "Date"]],
        body: recentOrders.map((o) => [o.customerName, `$${o.totalAmount.toFixed(0)}`, o.status, new Date(o.createdAt).toLocaleDateString()]),
        theme: "grid",
        headStyles: { fillColor: SECTION_COLORS.pink, textColor: [0, 0, 0], fontStyle: "bold", fontSize: 9 },
        bodyStyles: { fillColor: SECTION_COLORS.section, textColor: [255, 255, 255], fontSize: 9 },
        alternateRowStyles: { fillColor: SECTION_COLORS.row },
        margin: { left: 20, right: 20 },
      });
      y = (doc as any).lastAutoTable.finalY + 14;
    }

    if (lowStockProducts.length > 0) {
      if (y > 240) {
        doc.addPage();
        y = 20;
      }
      drawSectionTitle(doc, "Low Stock Alerts", y, pageWidth, SECTION_COLORS.red);
      y += 16;
      autoTable(doc, {
        startY: y,
        head: [["Product", "Stock"]],
        body: lowStockProducts.map((p) => [p.name, `${p.stock_quantity} units`]),
        theme: "grid",
        headStyles: { fillColor: SECTION_COLORS.red, textColor: [255, 255, 255], fontStyle: "bold", fontSize: 9 },
        bodyStyles: { fillColor: SECTION_COLORS.section, textColor: [255, 255, 255], fontSize: 9 },
        alternateRowStyles: { fillColor: SECTION_COLORS.row },
        margin: { left: 20, right: 20 },
      });
    }

    drawFooter(doc, pageWidth);
    doc.save(`${storeName.replace(/\s+/g, "_")}_Report.pdf`);
  };

  return (
    <button
      onClick={exportPDF}
      className="bg-gradient-to-br from-cyan-500 to-blue-600 text-white px-8 py-3 rounded-2xl font-black text-[11px] uppercase tracking-[0.2em] hover:scale-105 active:scale-95 transition-all shadow-[0_10px_30px_rgba(6,182,212,0.2)] flex items-center gap-3 print:hidden"
    >
      <FileDown className="w-4 h-4" /> Export PDF
    </button>
  );
}
