cloudinary upload "E:/multo2/temp_images/logo.png" --public_id "hotel2/logo" --overwrite
cloudinary upload "E:/multo2/temp_images/mobile-logo.png" --public_id "hotel2/mobile-logo" --overwrite
cloudinary upload "E:/multo2/temp_images/background/banner-bg-2.png" --public_id "hotel2/background/banner-bg-2" --overwrite
cloudinary upload "E:/multo2/temp_images/background/mobile-banner-2.png" --public_id "hotel2/background/mobile-banner-2" --overwrite
cloudinary upload "E:/multo2/temp_images/background/banner-bg.png" --public_id "hotel2/background/banner-bg" --overwrite
cloudinary upload "E:/multo2/temp_images/background/mobile-banner.png" --public_id "hotel2/background/mobile-banner" --overwrite
cloudinary upload "E:/multo2/temp_images/background/banner-bg-3.png" --public_id "hotel2/background/banner-bg-3" --overwrite
cloudinary upload "E:/multo2/temp_images/background/mobile-banner-3.png" --public_id "hotel2/background/mobile-banner-3" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-1.png" --public_id "hotel2/card-image/image-1" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/arrow-dark.png" --public_id "hotel2/icon/arrow-dark" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/bottom-shape.png" --public_id "hotel2/vector-shape/bottom-shape" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/double-bed-icon.png" --public_id "hotel2/icon/double-bed-icon" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/tv-icon.png" --public_id "hotel2/icon/tv-icon" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/food-icon.png" --public_id "hotel2/icon/food-icon" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-2.png" --public_id "hotel2/card-image/image-2" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-3.png" --public_id "hotel2/card-image/image-3" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-4.png" --public_id "hotel2/card-image/image-4" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/right-top.png" --public_id "hotel2/vector-shape/right-top" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/right-bottom.png" --public_id "hotel2/vector-shape/right-bottom" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/couple-room.png" --public_id "hotel2/card-image/couple-room" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/luxury-room-vec.png" --public_id "hotel2/vector-shape/luxury-room-vec" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/mobile-room.png" --public_id "hotel2/vector-shape/mobile-room" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/family-room.png" --public_id "hotel2/card-image/family-room" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/deluxe-room.png" --public_id "hotel2/card-image/deluxe-room" --overwrite
cloudinary upload "E:/multo2/temp_images/bg-shape/right-corner-shape.png" --public_id "hotel2/bg-shape/right-corner-shape" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/center-shape.png" --public_id "hotel2/vector-shape/center-shape" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-8.png" --public_id "hotel2/card-image/image-8" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-9.png" --public_id "hotel2/card-image/image-9" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-10.png" --public_id "hotel2/card-image/image-10" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-11.png" --public_id "hotel2/card-image/image-11" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/top-left.png" --public_id "hotel2/vector-shape/top-left" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/top-right.png" --public_id "hotel2/vector-shape/top-right" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/washroom.png" --public_id "hotel2/icon/washroom" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/bottom-left.png" --public_id "hotel2/vector-shape/bottom-left" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/bottom-right.png" --public_id "hotel2/vector-shape/bottom-right" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/wiFi.png" --public_id "hotel2/icon/wiFi" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/sea.png" --public_id "hotel2/icon/sea" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/parking.png" --public_id "hotel2/icon/parking" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/pets.png" --public_id "hotel2/icon/pets" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/washing-machine.png" --public_id "hotel2/icon/washing-machine" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/activities-vec.png" --public_id "hotel2/vector-shape/activities-vec" --overwrite
cloudinary upload "E:/multo2/temp_images/user/1.png" --public_id "hotel2/user/1" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-12.png" --public_id "hotel2/card-image/image-12" --overwrite
cloudinary upload "E:/multo2/temp_images/user/2.png" --public_id "hotel2/user/2" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-13.png" --public_id "hotel2/card-image/image-13" --overwrite
cloudinary upload "E:/multo2/temp_images/user/3.png" --public_id "hotel2/user/3" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-14.png" --public_id "hotel2/card-image/image-14" --overwrite
cloudinary upload "E:/multo2/temp_images/user/4.png" --public_id "hotel2/user/4" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-15.png" --public_id "hotel2/card-image/image-15" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/1.png" --public_id "hotel2/gallery/1" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/2.png" --public_id "hotel2/gallery/2" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/3.png" --public_id "hotel2/gallery/3" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/4.png" --public_id "hotel2/gallery/4" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/5.png" --public_id "hotel2/gallery/5" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/6.png" --public_id "hotel2/gallery/6" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/7.png" --public_id "hotel2/gallery/7" --overwrite
cloudinary upload "E:/multo2/temp_images/bg-shape/footer-bg-shape.png" --public_id "hotel2/bg-shape/footer-bg-shape" --overwrite
cloudinary upload "E:/multo2/temp_images/footer-logo.png" --public_id "hotel2/footer-logo" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/down-arrow.png" --public_id "hotel2/icon/down-arrow" --overwrite
cloudinary upload "E:/multo2/temp_images/vector/attached.png" --public_id "hotel2/vector/attached" --overwrite
cloudinary upload "E:/multo2/temp_images/bg-shape/top-left-corner-shape.png" --public_id "hotel2/bg-shape/top-left-corner-shape" --overwrite
cloudinary upload "E:/multo2/temp_images/bg-shape/top-right-corner-shape.png" --public_id "hotel2/bg-shape/top-right-corner-shape" --overwrite
cloudinary upload "E:/multo2/temp_images/bg-shape/heading-mobile-shape.png" --public_id "hotel2/bg-shape/heading-mobile-shape" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/testimonial-top-vec.png" --public_id "hotel2/vector-shape/testimonial-top-vec" --overwrite
cloudinary upload "E:/multo2/temp_images/bg-shape/heading-mobile-shape-2.png" --public_id "hotel2/bg-shape/heading-mobile-shape-2" --overwrite
cloudinary upload "E:/multo2/temp_images/vector/form-texture.png" --public_id "hotel2/vector/form-texture" --overwrite
cloudinary upload "E:/multo2/temp_images/bg-shape/footer-bgShape.png" --public_id "hotel2/bg-shape/footer-bgShape" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/banner-bottom-shape.png" --public_id "hotel2/vector-shape/banner-bottom-shape" --overwrite
cloudinary upload "E:/multo2/temp_images/bg-shape/booking-bg-shape.png" --public_id "hotel2/bg-shape/booking-bg-shape" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/mobile-booking-outer.png" --public_id "hotel2/vector-shape/mobile-booking-outer" --overwrite
cloudinary upload "E:/multo2/temp_images/bg-shape/booking-shape.png" --public_id "hotel2/bg-shape/booking-shape" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/mobile-booking-vec.png" --public_id "hotel2/vector-shape/mobile-booking-vec" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/top-shape.png" --public_id "hotel2/vector-shape/top-shape" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/body-right.png" --public_id "hotel2/vector-shape/body-right" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/body-left.png" --public_id "hotel2/vector-shape/body-left" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/room-gallery.png" --public_id "hotel2/vector-shape/room-gallery" --overwrite
cloudinary upload "E:/multo2/temp_images/background/title-banner.png" --public_id "hotel2/background/title-banner" --overwrite
cloudinary upload "E:/multo2/temp_images/background/title-banner-2.png" --public_id "hotel2/background/title-banner-2" --overwrite
cloudinary upload "E:/multo2/temp_images/background/title-banner-3.png" --public_id "hotel2/background/title-banner-3" --overwrite
cloudinary upload "E:/multo2/temp_images/background/title-banner-4.png" --public_id "hotel2/background/title-banner-4" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/header-outset.png" --public_id "hotel2/vector-shape/header-outset" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/header-inset.png" --public_id "hotel2/vector-shape/header-inset" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/team-cornor.png" --public_id "hotel2/vector-shape/team-cornor" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/calender.png" --public_id "hotel2/icon/calender" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/restaurant-vec.png" --public_id "hotel2/vector-shape/restaurant-vec" --overwrite
cloudinary upload "E:/multo2/temp_images/background/contact-image.png" --public_id "hotel2/background/contact-image" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/about-right.png" --public_id "hotel2/vector-shape/about-right" --overwrite
cloudinary upload "E:/multo2/temp_images/about/about-1.png" --public_id "hotel2/about/about-1" --overwrite
cloudinary upload "E:/multo2/temp_images/about/about-2.png" --public_id "hotel2/about/about-2" --overwrite
cloudinary upload "E:/multo2/temp_images/about/about-3.png" --public_id "hotel2/about/about-3" --overwrite
cloudinary upload "E:/multo2/temp_images/team/team-1.png" --public_id "hotel2/team/team-1" --overwrite
cloudinary upload "E:/multo2/temp_images/team/team-2.png" --public_id "hotel2/team/team-2" --overwrite
cloudinary upload "E:/multo2/temp_images/team/team-3.png" --public_id "hotel2/team/team-3" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/footer-shape.png" --public_id "hotel2/vector-shape/footer-shape" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/footer-shape-right.png" --public_id "hotel2/vector-shape/footer-shape-right" --overwrite
cloudinary upload "E:/multo2/temp_images/blog/blog-detail.png" --public_id "hotel2/blog/blog-detail" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/blog-detail-vec.png" --public_id "hotel2/vector-shape/blog-detail-vec" --overwrite
cloudinary upload "E:/multo2/temp_images/blog/blog-detail-1.png" --public_id "hotel2/blog/blog-detail-1" --overwrite
cloudinary upload "E:/multo2/temp_images/blog/blog-detail-2.png" --public_id "hotel2/blog/blog-detail-2" --overwrite
cloudinary upload "E:/multo2/temp_images/user/user-8.png" --public_id "hotel2/user/user-8" --overwrite
cloudinary upload "E:/multo2/temp_images/user/user-9.png" --public_id "hotel2/user/user-9" --overwrite
cloudinary upload "E:/multo2/temp_images/user/user-10.png" --public_id "hotel2/user/user-10" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/side-image-1.png" --public_id "hotel2/gallery/side-image-1" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/side-image-2.png" --public_id "hotel2/gallery/side-image-2" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/side-image-3.png" --public_id "hotel2/gallery/side-image-3" --overwrite
cloudinary upload "E:/multo2/temp_images/blog/blog-card-1.png" --public_id "hotel2/blog/blog-card-1" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/blog-vec.png" --public_id "hotel2/vector-shape/blog-vec" --overwrite
cloudinary upload "E:/multo2/temp_images/user/user-7.png" --public_id "hotel2/user/user-7" --overwrite
cloudinary upload "E:/multo2/temp_images/blog/blog-card-2.png" --public_id "hotel2/blog/blog-card-2" --overwrite
cloudinary upload "E:/multo2/temp_images/blog/blog-card-3.png" --public_id "hotel2/blog/blog-card-3" --overwrite
cloudinary upload "E:/multo2/temp_images/blog/blog-card-4.png" --public_id "hotel2/blog/blog-card-4" --overwrite
cloudinary upload "E:/multo2/temp_images/blog/blog-card-5.png" --public_id "hotel2/blog/blog-card-5" --overwrite
cloudinary upload "E:/multo2/temp_images/blog/blog-card-6.png" --public_id "hotel2/blog/blog-card-6" --overwrite
cloudinary upload "E:/multo2/temp_images/blog/blog-card-7.png" --public_id "hotel2/blog/blog-card-7" --overwrite
cloudinary upload "E:/multo2/temp_images/blog/blog-card-8.png" --public_id "hotel2/blog/blog-card-8" --overwrite
cloudinary upload "E:/multo2/temp_images/blog/blog-card-9.png" --public_id "hotel2/blog/blog-card-9" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/booking-image.png" --public_id "hotel2/card-image/booking-image" --overwrite
cloudinary upload "E:/multo2/temp_images/cs-logo.png" --public_id "hotel2/cs-logo" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/gallery-1.png" --public_id "hotel2/gallery/gallery-1" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/gallery-2.png" --public_id "hotel2/gallery/gallery-2" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/gallery-3.png" --public_id "hotel2/gallery/gallery-3" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/gallery-4.png" --public_id "hotel2/gallery/gallery-4" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/gallery-5.png" --public_id "hotel2/gallery/gallery-5" --overwrite
cloudinary upload "E:/multo2/temp_images/gallery/gallery-6.png" --public_id "hotel2/gallery/gallery-6" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/restaurant-1.png" --public_id "hotel2/card-image/restaurant-1" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/restaurant-2.png" --public_id "hotel2/card-image/restaurant-2" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/restaurant-3.png" --public_id "hotel2/card-image/restaurant-3" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/menu-1.png" --public_id "hotel2/card-image/menu-1" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/menu-vec.png" --public_id "hotel2/vector-shape/menu-vec" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/menu-2.png" --public_id "hotel2/card-image/menu-2" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/menu-3.png" --public_id "hotel2/card-image/menu-3" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/menu-4.png" --public_id "hotel2/card-image/menu-4" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/menu-5.png" --public_id "hotel2/card-image/menu-5" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/menu-6.png" --public_id "hotel2/card-image/menu-6" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/menu-7.png" --public_id "hotel2/card-image/menu-7" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/menu-8.png" --public_id "hotel2/card-image/menu-8" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/menu-9.png" --public_id "hotel2/card-image/menu-9" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/king-bed.png" --public_id "hotel2/icon/king-bed" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/led-tv.png" --public_id "hotel2/icon/led-tv" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/breakfast.png" --public_id "hotel2/icon/breakfast" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/washing-machine-2.png" --public_id "hotel2/icon/washing-machine-2" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/internet-wifi.png" --public_id "hotel2/icon/internet-wifi" --overwrite
cloudinary upload "E:/multo2/temp_images/icon/swimming-pool.png" --public_id "hotel2/icon/swimming-pool" --overwrite
cloudinary upload "E:/multo2/temp_images/user/user-5.png" --public_id "hotel2/user/user-5" --overwrite
cloudinary upload "E:/multo2/temp_images/user/user-6.png" --public_id "hotel2/user/user-6" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-16.png" --public_id "hotel2/card-image/image-16" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-17.png" --public_id "hotel2/card-image/image-17" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-18.png" --public_id "hotel2/card-image/image-18" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/image-19.png" --public_id "hotel2/card-image/image-19" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/double-room.png" --public_id "hotel2/card-image/double-room" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/single-room.png" --public_id "hotel2/card-image/single-room" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/spa-main-img.png" --public_id "hotel2/card-image/spa-main-img" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/spa-vec.png" --public_id "hotel2/vector-shape/spa-vec" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/spa-content-vec.png" --public_id "hotel2/vector-shape/spa-content-vec" --overwrite
cloudinary upload "E:/multo2/temp_images/vector-shape/spa-mobile-corner.png" --public_id "hotel2/vector-shape/spa-mobile-corner" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/spa-image-1.png" --public_id "hotel2/card-image/spa-image-1" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/spa-image-2.png" --public_id "hotel2/card-image/spa-image-2" --overwrite
cloudinary upload "E:/multo2/temp_images/card-image/spa-image-3.png" --public_id "hotel2/card-image/spa-image-3" --overwrite
cloudinary upload "E:/multo2/temp_images/video/hotel-video.mp4" --public_id "hotel2/video/hotel-video" --resource_type video --overwrite