import { create } from 'zustand';
import { persist } from 'zustand/middleware';

interface LanguageState {
  language: 'en' | 'ar';
  setLanguage: (lang: 'en' | 'ar') => void;
  t: (key: string) => string;
}

export const translations = {
  en: {
    home: "Home",
    shop: "Shop",
    shopAll: "Shop All",
    collections: "Collections",
    categories: "Categories",
    boutique: "Boutique",
    drop: "Drop",
    search: "Search...",
    myAccount: "My Account",
    adminPanel: "Admin Panel",
    signOut: "Sign Out",
    signIn: "Sign In",
    createAccount: "Create Account",
    
    // Storefront General
    addToCart: "Add to Cart",
    cart: "Cart",
    featuredProducts: "Featured Products",
    exploreCollections: "Explore Collections",
    saleOffers: "Sale Offers",
    testimonials: "Testimonials",
    videoSection: "Video",
    marquee: "Announcement",
    aboutUs: "About Us",
    reviews: "Reviews",

    // Admin Sidebar
    overview: "Overview",
    products: "Products",
    orders: "Orders",
    mediaHub: "Media Hub",
    banners: "Banners",
    storeBuilder: "Store Builder",
    siteBuilder: "Site Builder",
    generalSettings: "General Settings",
    siteSettings: "Site Settings",
    platformStores: "Platform Stores",
    templates: "Templates",
    toursPackages: "Tours & Packages",
    bookingInquiries: "Booking Inquiries",
    bannersSliders: "Banners & Sliders",
    mainControl: "Main Control",
    systemAdmin: "System Admin",
    customization: "Customization",

    // Admin settings tabs and headers
    general: "General",
    theme: "Colors & Style",
    header: "Header & Navigation",
    signature: "Advanced Features",
    tracking: "Pixels & Tracking",
    business: "Shipping & Delivery",
    storeCore: "Store Core",
    masterControl: "Master control for your brand identity and ecosystem.",
    brandMatrix: "Brand Matrix",
    marketIdentity: "Market Identity (Title)",
    enterStoreName: "Enter Store Name",
    seoSignal: "SEO Signal (Description)",
    premiumExperience: "Premium e-commerce experience...",
    signatureLogo: "Signature Logo (Header)",
    browserNode: "Browser Node (Favicon)",
    saveChanges: "Save Changes",
    saving: "Saving...",
    settingsSaved: "Settings saved successfully",
    themeConfiguration: "Theme Configuration",
    primaryColor: "Primary Accent Color",
    logoUpload: "Logo Upload",
    navigationMenu: "Navigation Menu",
    logisticsGrids: "Logistics Grids",
    defineGrid: "Define Grid",
    zoneIdentifier: "Zone Identifier",
    rateValue: "Rate Value",
    livePulse: "Live Pulse Notifications",
    pulseInterval: "Pulse Interval (Seconds)",
    socialProof: "Social Proof Matrix",
    injectReview: "Inject Review",
    identity: "Identity",
    coordinates: "Coordinates",
    reviewContent: "Review Content",

    // Comm Channels (General Settings)
    commChannels: "Comm Channels",
    uplinkEmail: "Uplink Email",
    voiceDirect: "Voice Direct",
    secureWhatsapp: "Secure WhatsApp",
    faviconSpec: "Global standard: 32x32px or 64x64px Resource.",

    // Header topology (Header tab)
    headerTopology: "Header Topology",
    navigationNodes: "Navigation Nodes",
    injectLink: "+ Inject Link",
    label: "Label",
    uplinkPath: "Uplink Path",
    
    // Header Layouts
    legacyLayout: "Legacy",
    legacyLayoutDesc: "Original structure parameters.",
    symmetricLayout: "Symmetric",
    symmetricLayoutDesc: "Logo Left, Balanced Central Matrix.",
    focusLayout: "Focus",
    focusLayoutDesc: "Links Left, Identity Center Node.",
    discreteLayout: "Discrete",
    discreteLayoutDesc: "Stealth Identity, Action Focused.",
    luxuryLayout: "High-End",
    luxuryLayoutDesc: "Vertical Stacked Premium Identity.",
    fluidLayout: "Fluid",
    fluidLayoutDesc: "Mobile-First Dynamic Interface.",

    // Color Architecture (Theme tab)
    colorArchitecture: "Color Architecture",
    colorArchitectureDesc: "Define the visual DNA of your storefront across all modules.",
    aestheticSynthesis: "Aesthetic Synthesis Engine",
    globalColorControl: "Global Color Injection & Matrix Control",
    versionActive: "V4.0 Active",
    phaseA: "Phase A (Primary)",
    phaseB: "Phase B (Secondary)",
    flowPattern: "Flow Pattern",
    linearVertical: "Linear (Vertical)",
    linearHorizontal: "Linear (Horizontal)",
    diagonalFlow: "Diagonal (Flow)",
    radialCore: "Radial (Core)",
    injectionNode: "Injection Node",
    globalFullMesh: "Global (Full Mesh)",
    nexusHome: "Nexus (Home)",
    baseFooter: "Base (Footer)",
    archiveShop: "Archive (Shop)",
    neuralCategories: "Neural (Categories)",
    signalProduct: "Signal (Product)",
    gatewayCart: "Gateway (Cart)",
    secureCheckout: "Secure (Checkout)",
    targetStream: "Target Stream",
    atmosphereBg: "Atmosphere (BG)",
    frequencyText: "Frequency (Text)",
    kineticMotion: "Kinetic Motion",
    static: "Static",
    animated: "Animated",
    applySynthesis: "Apply Synthesis",
    syncToCloud: "Sync to Cloud",
    homePageLabel: "Home Page",
    homePageDesc: "Main entry point and landing experience.",
    productGalleryLabel: "Product Gallery",
    productGalleryDesc: "Main shop and product listing grid.",
    collectionsLabel: "Collections",
    collectionsDesc: "Category browsing and discovery.",
    productDetailsLabel: "Product Details",
    productDetailsDesc: "Individual product showcase page.",
    shoppingCartLabel: "Shopping Cart",
    shoppingCartDesc: "Review and cart management layer.",
    checkoutPhaseLabel: "Checkout Phase",
    checkoutPhaseDesc: "Transaction and secure payment node.",
    globalSignalFooter: "Global Signal & Footer Matrix",
    primaryBrandIdentity: "Primary Brand Identity",
    footerAtmosphereBg: "Footer Atmosphere (BG)",
    footerSignalText: "Footer Signal (Text)",

    // Financial Signal
    financialSignalMatrix: "Financial Signal Matrix",
    priceDynamicsControl: "Price Dynamics & Sale Pulse Control",
    economyModule: "Economy Module",
    corePriceSignal: "Core Price Signal (Regular)",
    standardRateColor: "Standard Rate Color",
    pulseSignalSale: "Pulse Signal (Sale Price)",
    discountPulseColor: "Discount Pulse Color",

    // Tracking
    observatoryPixels: "Observatory Pixels",
    metaPixel: "Meta Pixel",
    tiktokSignal: "TikTok Signal",
    snapProtocol: "Snap Protocol",
    analyticsG4: "Analytics G4",
    secretId: "Secret ID",

    // Protocol messages
    protocolSecured: "Protocol Secured",
    uplinkPending: "Uplink Pending"
  },
  ar: {
    home: "الرئيسية",
    shop: "المتجر",
    shopAll: "تسوق الكل",
    collections: "التشكيلات",
    categories: "الفئات",
    boutique: "البوتيك",
    drop: "الإصدارات",
    search: "بحث...",
    myAccount: "حسابي",
    adminPanel: "لوحة التحكم",
    signOut: "تسجيل الخروج",
    signIn: "تسجيل الدخول",
    createAccount: "إنشاء حساب",

    // Storefront General
    addToCart: "إضافة إلى السلة",
    cart: "سلة التسوق",
    featuredProducts: "المنتجات المميزة",
    exploreCollections: "استكشف المجموعات",
    saleOffers: "عروض التخفيضات",
    testimonials: "آراء العملاء",
    videoSection: "فيديو",
    marquee: "شريط الإعلانات",
    aboutUs: "من نحن",
    reviews: "التقييمات",

    // Admin Sidebar
    overview: "نظرة عامة",
    products: "المنتجات",
    orders: "الطلبات",
    mediaHub: "مكتبة الوسائط",
    banners: "البانرات",
    storeBuilder: "منشئ المتجر",
    siteBuilder: "منشئ الموقع",
    generalSettings: "الإعدادات العامة",
    siteSettings: "إعدادات الموقع",
    platformStores: "متاجر المنصة",
    templates: "القوالب",
    toursPackages: "الرحلات والبرامج",
    bookingInquiries: "طلبات الحجز",
    bannersSliders: "البانرات والشرائح",
    mainControl: "التحكم الرئيسي",
    systemAdmin: "إدارة النظام",
    customization: "التخصيص",

    // Admin settings tabs and headers
    general: "عام",
    theme: "الألوان والتصميم",
    header: "الهيدر والتنقل",
    signature: "خصائص متقدمة",
    tracking: "أكواد التتبع",
    business: "الشحن والتوصيل",
    storeCore: "إعدادات المتجر",
    masterControl: "التحكم الكامل في هوية علامتك التجارية ونظامك البيئي.",
    brandMatrix: "بيانات المتجر الأساسية",
    marketIdentity: "اسم المتجر",
    enterStoreName: "أدخل اسم المتجر",
    seoSignal: "وصف المتجر (SEO)",
    premiumExperience: "تجربة تسوق إلكتروني مميزة...",
    signatureLogo: "شعار المتجر (الهيدر)",
    browserNode: "أيقونة المتصفح (Favicon)",
    saveChanges: "حفظ التغييرات",
    saving: "جاري الحفظ...",
    settingsSaved: "تم حفظ الإعدادات بنجاح",
    themeConfiguration: "إعدادات المظهر",
    primaryColor: "اللون الأساسي للمتجر",
    logoUpload: "تحميل الشعار",
    navigationMenu: "قائمة التنقل",
    logisticsGrids: "مناطق وأسعار الشحن",
    defineGrid: "إضافة منطقة شحن",
    zoneIdentifier: "اسم المنطقة (مثال: الشحن المحلي)",
    rateValue: "تكلفة الشحن",
    livePulse: "إشعارات الشراء المباشرة",
    pulseInterval: "الفترة الزمنية بين الإشعارات (بالثواني)",
    socialProof: "آراء العملاء والمراجعات",
    injectReview: "إضافة مراجعة",
    identity: "الاسم",
    coordinates: "الوظيفة أو الموقع",
    reviewContent: "نص المراجعة",

    // Comm Channels (General Settings)
    commChannels: "قنوات الاتصال",
    uplinkEmail: "البريد الإلكتروني للاتصال",
    voiceDirect: "رقم الهاتف المباشر",
    secureWhatsapp: "رقم الواتساب الآمن",
    faviconSpec: "المقاس القياسي: 32x32 بكسل أو 64x64 بكسل.",

    // Header topology (Header tab)
    headerTopology: "تنسيق وهيكل الترويسة",
    navigationNodes: "روابط التنقل",
    injectLink: "+ إضافة رابط",
    label: "اسم الرابط",
    uplinkPath: "مسار الرابط",
    
    // Header Layouts
    legacyLayout: "تقليدي",
    legacyLayoutDesc: "المعايير والهيكلية الأصلية.",
    symmetricLayout: "متماثل",
    symmetricLayoutDesc: "الشعار على اليسار، مع روابط متوازنة في المنتصف.",
    focusLayout: "تركيز",
    focusLayoutDesc: "الروابط على اليسار، الشعار في المنتصف.",
    discreteLayout: "مبسط",
    discreteLayoutDesc: "شعار خفي، يركز على الإجراءات.",
    luxuryLayout: "فاخر",
    luxuryLayoutDesc: "هوية مكدسة رأسياً بمظهر فاخر.",
    fluidLayout: "مرن (همبرغر)",
    fluidLayoutDesc: "واجهة ديناميكية مصممة للهواتف أولاً.",

    // Color Architecture (Theme tab)
    colorArchitecture: "هندسة الألوان",
    colorArchitectureDesc: "حدد الهوية البصرية لمتجرك عبر جميع الصفحات.",
    aestheticSynthesis: "محرك دمج الجماليات",
    globalColorControl: "حقن الألوان العام والتحكم في المصفوفة",
    versionActive: "الإصدار 4.0 نشط",
    phaseA: "المرحلة أ (الأساسي)",
    phaseB: "المرحلة ب (الثانوي)",
    flowPattern: "نمط تدفق الألوان",
    linearVertical: "خطي (رأسي)",
    linearHorizontal: "خطي (أفقي)",
    diagonalFlow: "قطري (تدفق)",
    radialCore: "شعاعي (مركزي)",
    injectionNode: "مكان تطبيق اللون",
    globalFullMesh: "عام (تطبيق كامل)",
    nexusHome: "الرئيسية (المركز)",
    baseFooter: "التذييل (القاعدة)",
    archiveShop: "المعرض (المتجر)",
    neuralCategories: "الأقسام",
    signalProduct: "صفحة المنتج",
    gatewayCart: "سلة المشتريات (Gateway)",
    secureCheckout: "الدفع الآمن (Secure)",
    targetStream: "العنصر المستهدف",
    atmosphereBg: "الخلفية (الغلاف)",
    frequencyText: "النصوص (Frequency)",
    kineticMotion: "الحركة والتفاعل",
    static: "ثابت",
    animated: "متحرك",
    applySynthesis: "تطبيق التدرج",
    syncToCloud: "حفظ ومزامنة",
    homePageLabel: "الصفحة الرئيسية",
    homePageDesc: "نقطة الدخول الرئيسية وتجربة الهبوط.",
    productGalleryLabel: "معرض المنتجات",
    productGalleryDesc: "صفحة المتجر الرئيسية وقائمة المنتجات.",
    collectionsLabel: "المجموعات والأقسام",
    collectionsDesc: "تصفح الأقسام واكتشاف المنتجات.",
    productDetailsLabel: "تفاصيل المنتج",
    productDetailsDesc: "صفحة عرض وتفاصيل المنتج الفردي.",
    shoppingCartLabel: "سلة التسوق",
    shoppingCartDesc: "مراجعة وإدارة السلة.",
    checkoutPhaseLabel: "مرحلة الدفع",
    checkoutPhaseDesc: "إتمام المعاملة والدفع الآمن.",
    globalSignalFooter: "التحكم الشامل وتذييل الصفحة",
    primaryBrandIdentity: "اللون الأساسي للعلامة التجارية",
    footerAtmosphereBg: "خلفية تذييل الصفحة",
    footerSignalText: "نص تذييل الصفحة",

    // Financial Signal
    financialSignalMatrix: "مصفوفة التحكم المالي والأسعار",
    priceDynamicsControl: "ديناميكيات الأسعار والتحكم بالعروض",
    economyModule: "وحدة الاقتصاد والمالية",
    corePriceSignal: "السعر الأساسي (الافتراضي)",
    standardRateColor: "لون السعر القياسي",
    pulseSignalSale: "السعر المخفض (العرض)",
    discountPulseColor: "لون سعر الخصم",

    // Tracking
    observatoryPixels: "وحدات بكسل التتبع والتحليل",
    metaPixel: "بكسل ميتا (فيسبوك)",
    tiktokSignal: "إشارات تيك توك",
    snapProtocol: "سناب شات",
    analyticsG4: "تحليلات جوجل (GA4)",
    secretId: "معرف بكسل التتبع (ID)",

    // Protocol messages
    protocolSecured: "تم حفظ الإعدادات بنجاح",
    uplinkPending: "بانتظار الحفظ والرفع"
  }
};

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'en',
      setLanguage: (lang) => set({ language: lang }),
      t: (key: string) => {
        const lang = get().language;
        // @ts-ignore
        return translations[lang][key] || key;
      }
    }),
    {
      name: 'language-storage',
    }
  )
);
