import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export const translations = {
  en: {
    home: "Home",
    shop: "Shop",
    shopAll: "Shop All",
    collections: "Collections",
    categories: "Categories",
    boutique: "Boutique",
    drop: "Drop",
    search: "Search...",
    myAccount: "My Account",
    adminPanel: "Admin Panel",
    signOut: "Sign Out",
    signIn: "Sign In",
    createAccount: "Create Account",
    
    // Storefront General
    addToCart: "Add to Cart",
    cart: "Cart",
    featuredProducts: "Featured Products",
    exploreCollections: "Explore Collections",
    saleOffers: "Sale Offers",
    testimonials: "Testimonials",
    videoSection: "Video",
    marquee: "Announcement",
    aboutUs: "About Us",
    reviews: "Reviews",

    // Admin Sidebar
    overview: "Overview",
    products: "Products",
    orders: "Orders",
    mediaHub: "Media Hub",
    banners: "Banners",
    storeBuilder: "Store Builder",
    siteBuilder: "Site Builder",
    generalSettings: "General Settings",
    siteSettings: "Site Settings",
    platformStores: "Platform Stores",
    templates: "Templates",
    customers: "Customers",
    toursPackages: "Tours & Packages",
    bookingInquiries: "Booking Inquiries",
    bannersSliders: "Banners & Sliders",
    mainControl: "Main Control",
    systemAdmin: "System Admin",
    customization: "Customization",

    // Admin settings tabs and headers
    general: "General",
    theme: "Colors & Style",
    header: "Header & Navigation",
    signature: "Advanced Features",
    tracking: "Pixels & Tracking",
    business: "Shipping & Delivery",
    storeCore: "Store Core",
    masterControl: "Master control for your brand identity and ecosystem.",
    brandMatrix: "Brand Matrix",
    marketIdentity: "Market Identity (Title)",
    enterStoreName: "Enter Store Name",
    seoSignal: "SEO Signal (Description)",
    premiumExperience: "Premium e-commerce experience...",
    signatureLogo: "Signature Logo (Header)",
    browserNode: "Browser Node (Favicon)",
    saveChanges: "Save Changes",
    saving: "Saving...",
    settingsSaved: "Settings saved successfully",
    themeConfiguration: "Theme Configuration",
    primaryColor: "Primary Accent Color",
    logoUpload: "Logo Upload",
    navigationMenu: "Navigation Menu",
    logisticsGrids: "Logistics Grids",
    defineGrid: "Define Grid",
    zoneIdentifier: "Zone Identifier",
    rateValue: "Rate Value",
    livePulse: "Live Pulse Notifications",
    pulseInterval: "Pulse Interval (Seconds)",
    socialProof: "Social Proof Matrix",
    injectReview: "Inject Review",
    identity: "Identity",
    coordinates: "Coordinates",
    reviewContent: "Review Content",

    // Comm Channels (General Settings)
    commChannels: "Comm Channels",
    uplinkEmail: "Uplink Email",
    voiceDirect: "Voice Direct",
    secureWhatsapp: "Secure WhatsApp",
    faviconSpec: "Global standard: 32x32px or 64x64px Resource.",

    // Header topology (Header tab)
    headerTopology: "Header Topology",
    navigationNodes: "Navigation Nodes",
    injectLink: "+ Inject Link",
    label: "Label",
    uplinkPath: "Uplink Path",
    
    // Header Layouts
    legacyLayout: "Legacy",
    legacyLayoutDesc: "Original structure parameters.",
    symmetricLayout: "Symmetric",
    symmetricLayoutDesc: "Logo Left, Balanced Central Matrix.",
    focusLayout: "Focus",
    focusLayoutDesc: "Links Left, Identity Center Node.",
    discreteLayout: "Discrete",
    discreteLayoutDesc: "Stealth Identity, Action Focused.",
    luxuryLayout: "High-End",
    luxuryLayoutDesc: "Vertical Stacked Premium Identity.",
    fluidLayout: "Fluid",
    fluidLayoutDesc: "Mobile-First Dynamic Interface.",

    // Color Architecture (Theme tab)
    colorArchitecture: "Color Architecture",
    colorArchitectureDesc: "Define the visual DNA of your storefront across all modules.",
    aestheticSynthesis: "Aesthetic Synthesis Engine",
    globalColorControl: "Global Color Injection & Matrix Control",
    versionActive: "V4.0 Active",
    phaseA: "Phase A (Primary)",
    phaseB: "Phase B (Secondary)",
    flowPattern: "Flow Pattern",
    linearVertical: "Linear (Vertical)",
    linearHorizontal: "Linear (Horizontal)",
    diagonalFlow: "Diagonal (Flow)",
    radialCore: "Radial (Core)",
    injectionNode: "Injection Node",
    globalFullMesh: "Global (Full Mesh)",
    nexusHome: "Nexus (Home)",
    baseFooter: "Base (Footer)",
    archiveShop: "Archive (Shop)",
    neuralCategories: "Neural (Categories)",
    signalProduct: "Signal (Product)",
    gatewayCart: "Gateway (Cart)",
    secureCheckout: "Secure (Checkout)",
    targetStream: "Target Stream",
    atmosphereBg: "Atmosphere (BG)",
    frequencyText: "Frequency (Text)",
    kineticMotion: "Kinetic Motion",
    static: "Static",
    animated: "Animated",
    applySynthesis: "Apply Synthesis",
    syncToCloud: "Sync to Cloud",
    homePageLabel: "Home Page",
    homePageDesc: "Main entry point and landing experience.",
    productGalleryLabel: "Product Gallery",
    productGalleryDesc: "Main shop and product listing grid.",
    collectionsLabel: "Collections",
    collectionsDesc: "Category browsing and discovery.",
    productDetailsLabel: "Product Details",
    productDetailsDesc: "Individual product showcase page.",
    shoppingCartLabel: "Shopping Cart",
    shoppingCartDesc: "Review and cart management layer.",
    checkoutPhaseLabel: "Checkout Phase",
    checkoutPhaseDesc: "Transaction and secure payment node.",
    globalSignalFooter: "Global Signal & Footer Matrix",
    primaryBrandIdentity: "Primary Brand Identity",
    footerAtmosphereBg: "Footer Atmosphere (BG)",
    footerSignalText: "Footer Signal (Text)",

    // Financial Signal
    financialSignalMatrix: "Financial Signal Matrix",
    priceDynamicsControl: "Price Dynamics & Sale Pulse Control",
    economyModule: "Economy Module",
    corePriceSignal: "Core Price Signal (Regular)",
    standardRateColor: "Standard Rate Color",
    pulseSignalSale: "Pulse Signal (Sale Price)",
    discountPulseColor: "Discount Pulse Color",

    // Tracking
    observatoryPixels: "Observatory Pixels",
    metaPixel: "Meta Pixel",
    tiktokSignal: "TikTok Signal",
    snapProtocol: "Snap Protocol",
    analyticsG4: "Analytics G4",
    secretId: "Secret ID",

    // Protocol messages
    protocolSecured: "Protocol Secured",
    uplinkPending: "Uplink Pending",

    // Dashboard
    websiteAnalytics: "Website Analytics",
    analyticsDashboard: "Analytics Dashboard",
    websiteAnalyticsDesc: "Comprehensive overview of your showcase website and booking inquiries.",
    analyticsDashboardDesc: "Comprehensive overview of your store's digital performance.",
    inquiryLeads: "Inquiry Leads",
    totalRevenue: "Total Revenue",
    uniqueLeads: "Unique Leads",
    responseRate: "Response Rate",
    vsLastMonth: "Vs Last Month",
    pageVisits: "Page Visits",
    totalOrders: "Total Orders",
    conversionRate: "Conversion",
    trafficSource: "Traffic Source",
    avgValue: "Avg Value",
    activePackages: "Active Packages",
    inStock: "In Stock",
    showcaseLive: "Showcase Live",
    needsAttention: "Needs Attention",
    tourismTemplate: "Tourism Template",
    activeProducts: "Active Products",
    leadsFunnel: "Leads Funnel",
    salesFunnel: "Sales Funnel",
    websiteVisits: "Website Visits",
    addToCartLabel: "Add to Cart",
    packageClicks: "Package Clicks",
    checkoutLabel: "Checkout",
    inquiriesSubmitted: "Inquiries Submitted",
    purchasedLabel: "Purchased",
    goalLabel: "Goal",
    popularPackages: "Popular Packages",
    bestSellers: "Best Sellers",
    inquiriesReceived: "Inquiries Received",
    unitsSold: "Units Sold",
    inquiryActivity: "Inquiry Activity",
    activityHeatmap: "Activity Heatmap",

    // Dashboard extras
    organicDirect: "Organic Direct",
    active: "Active",
    monthlyRevenueTrend: "Monthly Revenue Trend",
    live: "Live",
    daysOfWeek: "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    at: "at",
    on: "on",

    // Products / Assets
    inventoryVault: "Inventory Vault",
    controlProductPrecision: "Control your product ecosystem with precision.",
    addNewAsset: "Add New Asset",
    physicalAsset: "Physical Asset",
    servicePackage: "Service / Package",
    assetDesignation: "Asset Designation",
    assetNarrative: "Asset Narrative",
    baseValuation: "Base Valuation ($)",
    flashDiscount: "Flash Discount ($)",
    dimensionScale: "Dimension Scale",
    universalScale: "Universal Scale",
    colorSpectrum: "Color Spectrum",
    addSizePlaceholder: "Add size (e.g. XL, 42)...",
    add: "Add",
    confirmDeleteProduct: "Are you sure you want to delete this product?",

    // Banners
    motionCanvas: "Motion Canvas",
    curateVisualNarrative: "Curate your store's high-impact visual narrative.",
    sliderDynamics: "Slider Dynamics",
    globalTransitionProtocols: "Global behavior and transition protocols.",
    autoCycle: "Automatic Cycle",
    latencyMs: "Latency (MS)",
    morphEffect: "Morph Effect",
    uiControls: "UI Controls",
    tactileArrows: "Tactile Arrows",
    progressMap: "Progress Map",
    visualNodes: "Visual Nodes",
    frameInventory: "Frame Inventory",
    appendFrame: "Append Frame",
    noMediaProjected: "No Media Projected",
    initializeCinematicFrame: "Initialize your first cinematic frame to establish store presence.",
    launchSequence: "Launch Sequence",
    frame: "Frame",
    productionStatus: "Production Status",
    mainDistribution: "Main Distribution (16:9)",
    mobileNode: "Mobile Node (9:16)",
    manifestTitle: "Manifest Title",
    supportingNarrative: "Supporting Narrative",
    triggerText: "Trigger Text",
    deploymentUrl: "Deployment URL",
    renderActionUi: "Render Action UI",
    spatialPosition: "Spatial Position",
    visualArchitecture: "Visual Architecture",
    spatialContext: "Spatial Context",
    definePreciseGeographicalCoordinates: "Define the precise geographical coordinates of this frame within your storefront architecture.",
    commitToRegistry: "Commit to Registry",

    // Categories
    collectionHub: "Collection Hub",
    architectNavStructure: "Architect your store's navigational structure.",
    syncSuccessful: "Sync Successful",
    commitChanges: "Commit Changes",
    newCollection: "New Collection",
    visualMatrix: "Visual Matrix",
    defineStorefrontAesthetic: "Define your storefront aesthetic.",
    landingPage: "Landing Page",
    allCollections: "All Collections",
    modifySector: "Modify Sector",
    registerNewSector: "Register New Sector",
    sectorDesignation: "Sector Designation",
    narrativeDescription: "Narrative Description",
    structuralHierarchy: "Structural Hierarchy",
    visualSignature: "Visual Signature",
    collectionIdentity: "Collection Identity",
    registryCode: "Registry Code",
    operations: "Operations",
    confirmDeleteCategory: "Are you sure you want to delete this category?",

    // Orders
    orderStream: "Order Stream",
    realtimeTransactionMatrix: "Real-time transaction matrix and fulfillment control.",
    scanningMatrix: "Scanning Matrix...",
    activeRecords: "Active Records",
    noActiveTransactions: "No active transactions",
    node: "Node",
    revenue: "Revenue",
    matrixUnits: "Matrix Units",
    timeStamp: "Time Stamp",
    statusLabel: "Status",
    verified: "Verified",
    loadMoreOrders: "Load More Orders",
    syncingNextNode: "Syncing Next Node...",
    orderAnalysis: "Order Analysis",
    uplink: "Uplink",
    awaitingSelection: "Awaiting Selection",
    clickTransactionNode: "Click on a transaction node to initiate detailed analysis and fulfillment.",
    identityLogistics: "Identity & Logistics",
    subject: "Subject",
    deliveryCoordinates: "Delivery Coordinates",
    noCoordinatesProvided: "No coordinates provided",
    commChannel: "Comm Channel",
    productMatrix: "Product Matrix",
    customerIntelligence: "Customer Intelligence / Notes",
    accumulatedTotal: "Accumulated Total",
    protocolExecution: "Protocol Execution",

    // Colors
    advancedColorControls: "Advanced Color Controls",
    controlColorAspect: "Control every single color aspect for each specific template.",
    primaryAccentColor: "Primary Accent Color",
    mainBackground: "Main Background",
    mainTextColor: "Main Text Color",
    headerBackgroundLabel: "Header Background",
    headerTextLabel: "Header Text",
    footerBackgroundLabel: "Footer Background",
    footerTextLabel: "Footer Text",
    primaryButtonBackground: "Primary Button Background",
    primaryButtonText: "Primary Button Text",
    priceTextColor: "Price Text Color",
    salePriceColorLabel: "Sale Price Color",
    saveColors: "Save Colors",
    colorsSavedSuccessfully: "Colors saved successfully!",
    failedToSaveColors: "Failed to save colors. Please try again.",

    // Media
    assetVault: "Asset Vault",
    centralizedRepository: "Centralized repository for your store's visual resources.",
    items: "Items",
    activeResourceInventory: "Active Resource Inventory",
    newDeployment: "New Deployment",
    initializeAsset: "Initialize Asset",
    registerNewResource: "Register new resource to the vault",
    sourceProtocolUrl: "Source Protocol (URL)",
    directLinkExternal: "Direct link from external distribution node.",
    abort: "Abort",
    deployAsset: "Deploy Asset",
    nullOutput: "Null Output",
    confirmDeleteAsset: "Are you sure you want to delete this asset?",
    zeroAssetsDetected: "Zero Assets Detected",
    vaultCurrentlyEmpty: "Vault is currently empty. Initialize a new resource deployment to begin building your visual library.",
    startDeploymentSequence: "Start Deployment Sequence",

    // Storefront
    buyNow: "Buy Now",
    processing: "Processing...",
    soldOut: "Sold Out",
    productDetails: "Product Details",
    colorSelection: "Color Selection",
    sizeLabel: "Size",
    sizeGuide: "Size Guide",
    quantityLabel: "Quantity",
    securePayment: "Secure Checkout",
    fastDelivery: "Fast Delivery",
    easyReturns: "Easy Returns",
    youMayAlsoLike: "You May Also Like",
    customerReviews: "Customer Reviews",
    writeReview: "Write a Review",
    submitReview: "Submit Review",
    noReviewsYet: "No reviews yet. Be the first!",
    unitsAvailable: "Units Available",
    yourCartIsEmpty: "Your cart is empty",
    shoppingCart: "Shopping Cart",
    deliveryDetails: "Delivery Details",
    paymentMethod: "Payment Method",
    orderSummary: "Summary",
    subtotal: "Subtotal",
    deliveryLabel: "Delivery",
    complimentary: "Complimentary",
    totalLabel: "Total",
    discountLabel: "Discount",
    couponCode: "Coupon Code",
    applyCode: "Apply",
    couponPlaceholder: "Coupon Code",
    completePurchase: "Complete Purchase",
    encryptedSecure: "Encrypted & Secure",
    orderNotes: "Order Notes (Optional)",
    shippingAddress: "Shipping Address",
    fullName: "Full Name",
    emailAddress: "Email Address",
    password: "Password",
    phoneNumber: "Phone Number",
    loggedInAs: "Logged in as",
    orderHistory: "Order History",
    noOrdersYet: "No orders yet",
    startShopping: "Start Shopping",
    orderNum: "Order #",
    statusColon: "Status:",
    orderedOn: "Ordered on",
    totalAmountColon: "Total Amount",
    previousPage: "← Previous Page",
    nextPage: "Next Page →",
    pageOf: "Page {page} of {total}",
    blog: "Blog",
    backToBlog: "← Back to Blog",
    noPostsYet: "No posts yet.",
    readMore: "Read",
    blogManager: "Blog Manager",
    managePosts: "Manage your store's blog posts.",
    newPost: "New Post",
    cancelBtn: "Cancel",
    createPost: "Create Post",
    titleField: "Title",
    slugField: "Slug",
    excerptField: "Excerpt",
    contentHtml: "Content (HTML)",
    imageField: "Image",
    publishPost: "Publish Post",
    loadingLabel: "Loading...",
    publishedLabel: "Published",
    draftLabel: "Draft",
    deleteLabel: "Delete",
    wishlist: "Wishlist",
    wishlistEmpty: "Your wishlist is empty.",
    browseProducts: "Browse Products",
    viewProduct: "View Product",
    addToWishlist: "Add to Wishlist",
    inYourWishlist: "In Your Wishlist",
    newsletter: "Newsletter",
    subscribeBtn: "Subscribe",
    subscribing: "Subscribing...",
    thanksSubscribing: "Thanks for subscribing!",
    subscribeText: "Subscribe for exclusive drops and offers.",
    contactUs: "Contact Us",
    clientService: "Client Service",
    houseMatters: "House Matters",
    shippingReturns: "Shipping & Returns",
    trackOrder: "Track Order",
    appointments: "Appointments",
    sustainability: "Sustainability",
    heritage: "Heritage",
    careers: "Careers",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    storeNotFound: "Store Not Found",
    storeNotFoundDesc: "The requested store does not exist.",
    allRightsReserved: "All Rights Reserved.",

    // Storefront pages (keys that were missing)
    welcomeStore: "Welcome to our official store.",
    exploreProducts: "Explore Products",
    storeSuspended: "Store Suspended",
    suspendedDesc: "This store is currently undergoing maintenance or has been temporarily deactivated by the platform administrator. Please check back later.",
    backToHome: "Back to Home",
    homeBreadcrumb: "Home",
    allItems: "All Items",
    sortBy: "Sort by:",
    featured: "Featured",
    priceLowHigh: "Price: Low to High",
    priceHighLow: "Price: High to Low",
    newest: "Newest",
    noProductsFound: "No products found",
    noProductsDesc: "We couldn't find any products in this collection.",
    clearFilters: "Clear Filters",
    saleBadge: "SALE",
    viewDetails: "View Details",
    allCollectionsTitle: "All Collections",
    allCollectionsDesc: "Explore our full range of premium essentials.",
    saleTitle: "Sale",
    saleDesc: "Premium items at exceptional value.",
    emptyCollection: "Empty Collection",
    emptyCollectionDesc: "We couldn't find any products in this selection.",
    exploreAll: "Explore All",
    premiumTravelPackage: "Premium Travel Package",
    curatedPackage: "Curated Package",
    privateGroupTours: "Private or Group Tours",
    perTraveler: "/ Per Traveler",
    bookThisTour: "Book This Tour Package",
    fullNamePlaceholder: "e.g. John Doe",
    phonePlaceholder: "e.g. +201000000000",
    departureDate: "Estimated Date of Departure",
    numberOfTravelers: "Number of Travelers",
    specialRequests: "Special Requests or Notes",
    requestsPlaceholder: "Specify hotel preferences, dietary requests, or custom duration.",
    submitting: "Submitting Inquiry...",
    sendBooking: "Send Booking Inquiry",
    inquiryReceived: "Inquiry Received!",
    inquiryReceivedDesc: "Your booking request has been successfully submitted. We will contact you shortly.",
    fullNameRequired: "Full Name and Phone Number are required.",
    bookingFailed: "Failed to submit booking inquiry.",
    onlyLeft: "Only {count} left - Order soon!",
    maxStockReached: "Maximum available stock reached",
    addedViewCart: "Added! View Cart",
    unavailable: "Unavailable",
    selectColor: "Select Color",
    selectSize: "Select Size",
    lowStock: "Low Stock: {count} Units",
    inventoryAvailable: "Inventory Available",
    addToBag: "Add to Bag",
    globalShipping: "Global Shipping",
    productGuarantee: "Product Guarantee",
    saleOffer: "Sale Offer",
    cartEmptyDesc: "Looks like you haven't added anything to your cart yet.",
    continueShopping: "Continue Shopping",
    shippingCalc: "Calculated at checkout",
    proceedToCheckout: "Proceed to Checkout",
    removeItemBtn: "Remove",
    welcomeBack: "Welcome Back",
    signInToTrack: "Sign in to track your orders and manage your account.",
    forgotPassword: "Forgot Password?",
    noAccount: "Don't have an account?",
    registerNow: "Register now",
    joinUs: "Join us to manage your shopping experience",
    fullNameLabel: "Full Name",
    haveAccount: "Already have an account?",
    signInLink: "Sign in",
    searchResults: "Search Results",
    showingResults: 'Showing results for "{query}"',
    searchPlaceholder2: "Search our store",
    searchDesc: "Enter a keyword to find products.",
    noProductsMatch: 'We couldn\'t find any products matching "{query}".',
    browseAllProducts: "Browse All Products",
    ourCollections: "Our Collections",
    itemsCount: "{count} Items",
    productsCount: "{count} Products",
    faqHeading: "Frequently Asked Questions",
    faqDesc: "Find answers to common questions about our products, shipping, and returns.",
    stillQuestions: "Still have questions?",
    stillQuestionsDesc: "Our support team is here to help.",
    contactSupport: "Contact Support",
    getInTouch: "Get in Touch",
    getInTouchDesc: "We'd love to hear from you. Get in touch with our team.",
    contactInfo: "Contact Information",
    ourStudio: "Our Studio",
    studioAddress: "123 Luxury Avenue, Design District, Cairo, Egypt 11511",
    emailUs: "Email Us",
    supportEmail: "support@luxestore.com",
    callUs: "Call Us",
    callHours: "Mon-Fri from 9am to 6pm.",
    callPhone: "+20 102 557 4570",
    whatsappSupport: "WhatsApp Support",
    whatsappDesc: "For the fastest response, reach us on WhatsApp.",
    chatWhatsApp: "Chat on WhatsApp",
    sendMessage: "Send us a Message",
    sendMessageBtn: "Send Message",
    shippingHeading: "Shipping & Returns",
    shippingDesc: "Everything you need to know about our shipping and return policies.",
    shippingPolicy: "Shipping Policy",
    domesticShipping: "Domestic Shipping (US)",
    internationalShipping: "International Shipping",
    processingTime: "Processing Times",
    returnPolicy: "Return Policy",
    howToReturn: "How to Return",
    orderConfirmed: "Order Confirmed",
    orderConfirmedDesc: "Thank you for your purchase! You'll receive a confirmation email shortly.",
    orderNumber: "Order Number",
    verifyEmail: "Verify Your Email",
    verifyDesc: "Enter the 6-digit code sent to your email",
    verifyBtn: "Verify Email",
    verifiedRedirect: "Verified! Redirecting...",
    noEmailFound: "No email found.",
    enterFullCode: "Please enter the full 6-digit code.",
    loadingReviews: "Loading...",
    reviewThankYou: "Thank you for your review!",
    reviewPlaceholder: "Share your experience (optional)",
    yourName: "Your Name",
    ratingLabel: "Rating:",
    reviewSuccess: "Review submitted!",
    searchOrders: "Search orders (Name, Email, Phone, ID)...",
    searchOrdersPlaceholder: "Search orders (Name, Email, Phone, ID)...",
    productNamePlaceholder: "e.g. Hyper-Light Sneakers",
    productDescPlaceholder: "Describe the essence of this product...",
    nonePlaceholder: "None",
    unknownSector: "Unknown Sector",
    createCategoryFirst: "Please create a category first before adding products.",
    errorAddingProduct: "Error adding product",
    deleteProductConfirm: "Are you sure you want to delete this product?",
    totalCustomers: "Total Customers",
    totalSpend: "Total Spend",
    totalSpendKpi: "Total Spend KPI",
    avgSpend: "Avg. Spend",
    noCustomersYet: "No Customers Yet",
    noCustomersDesc: "Once orders are placed, customers will appear here.",
    customerHead: "Customer",
    customerEmail: "Email",
    customerPhone: "Phone",
    customerOrders: "Orders",
    customerTotal: "Total",
    lastOrder: "Last Order",
    registeredCustomers: "{count} registered customers",
    postTitlePlaceholder: "Post title",
    postSlugPlaceholder: "post-slug",
    excerptPlaceholder: "Brief description",
    contentPlaceholder: "<p>Your post content here...</p>",
    savingLabel: "Saving...",
    noPostsYetAdmin: "No posts yet. Create your first post.",
    deletePostConfirm: "Delete this post?",
    authorDefault: "Admin",
    bannerNew: "New Banner",
    bannerSubtitle: "Add a catchy subtitle here",
    bannerBtnText: "Shop Now",
    bannerBtnLink: "/products",
    uhdRecommended: "UHD RECOMMENDED",
    portraitOptimized: "PORTRAIT OPTIMIZED",
    enterHeadline: "ENTER HEADLINE",
    defineVision: "Define the vision for this frame...",
    manifestSync: "Manifest Synchronized",
    awaitingInstruction: "Awaiting Instruction",
    alphaSynthesis: "Alpha Synthesis",
    alphaSynthesisDesc: "Remove background from header logo resource.",
    subjectName: "Subject Name",
    sectorLocation: "Sector / Location",
    inputSignal: "Input signal content...",
    deleteReview: "Delete Review",
    placeholderGlobal: "e.g. Global",
    bentoGrid: "Bento Grid",
    bentoGridDesc: "Premium cinematic mosaic",
    standardGrid: "Standard Grid",
    standardGridDesc: "Clean 4-column layout",
    horizontalScroll: "Horizontal Scroll",
    horizontalScrollDesc: "Sleek carousel strip",
    minimalList: "Minimal List",
    minimalListDesc: "Simple vertical list",
    circleBubbles: "Circle Bubbles",
    circleBubblesDesc: "Modern social-style bubbles",
    categoryPlaceholder: "e.g. Summer Essentials",
    categoryDescPlaceholder: "Elaborate on this collection's theme...",
    rootCollection: "ROOT COLLECTION",
    updateRegistry: "Update Registry",
    initializeSector: "Initialize Sector",
    cancelBtn2: "Cancel",
    nodeOf: "Node of",
    noMatrixData: "No Matrix Data",
    noMatrixDesc: "Initialize your first sector to begin deployment.",
    assetNamePlaceholder: "e.g. CORE_BANNER_ALPHA",
    assetUrlPlaceholder: "https://cdn.resource.com/...",
    noAssetsDetected: "Zero Assets Detected",
    noAssetsDesc: "Vault is currently empty. Initialize a new resource deployment to begin building your visual library.",
    startDeployment: "Start Deployment Sequence",
    hideFromUsers: "Hide from users",
    showToUsers: "Show to users",
    deleteForever: "Delete forever",
    modernCommerce: "Modern Commerce",
    zenithLuxury: "Zenith Luxury",
    signatureBrand: "Signature Brand",
    searchStores: "Search by store, slug, or owner...",
    activeStatus: "Active",
    suspendedStatus: "Suspended",
    storeDesign: "Store Design",
    deactivateStore: "Deactivate",
    reactivateStore: "Reactivate",
    permanentlyDelete: "Permanently Delete Store",
    confirmDeactivate: "Are you sure you want to DEACTIVATE this store?",
    confirmPermanentDelete: "CRITICAL WARNING: Are you sure you want to PERMANENTLY DELETE this store? This cannot be undone!",
    noStoresFound: "No stores found matching your search.",
    viewLiveStore: "View Live Store",
    addNewSection: "Add New Section",
    noSectionSelected: "No Section Selected",
    noSectionDesc: "Click on a section from the left sidebar to edit its content and style.",
    editContentStyle: "Edit content and visual style",
    saleSectionStyle: "Sale Section Style",
    contentSettings: "Content Settings",
    subtitleField: "Subtitle",
    sectionImage: "Section Image",
    tagline: "Tagline",
    taglinePlaceholder: "WHO WE ARE",
    primaryDescription: "Primary Description",
    secondaryDescription: "Secondary Description",
    testimonialDefault: "Excellent service!",
    addNew: "+ Add New",
    namePlaceholder: "Name",
    rolePlaceholder: "Role",
    testimonialPlaceholder: "Testimonial content...",
    scrollingTexts: "Scrolling Texts",
    addText: "+ Add Text",
    storefrontSaved: "Storefront layout saved!",
    welcomePlatform: "Welcome to our platform",
    discoverServices: "Discover amazing services",
    whatClientsSay: "What our clients say",
    whatCustomersSay: "What our customers say",
    shopByCategory: "Shop by Category",
    trendingNow: "Trending Now",
    newAnnouncement: "New Announcement",
    welcomeStoreTitle: "Welcome to our store",
    discoverProducts: "Discover amazing products",
    heroSection: "Hero Section",
    bannersSlider: "Banners Slider",
    categoriesSection: "Categories",
    featuredProductsSection: "Featured Products",
    aboutUsSection: "About Us",
    testimonialsSection: "Testimonials",
    richText: "Rich Text",
    announcementMarquee: "Announcement Marquee",
    websiteHero: "Hero Section",
    ourPackages: "Our Packages",
    dateAllTime: "All Time",
    dateToday: "Today",
    dateLast7: "Last 7 Days",
    dateThisMonth: "This Month",
    dateLastMonth: "Last Month",
    dateThisYear: "This Year",
    analyticsReport: "Analytics Report",
    generatedBy: "Generated by Shopora Analytics",
    keyMetrics: "Key Metrics",
    metricHeader: "Metric",
    valueHeader: "Value",
    detailHeader: "Detail",
    metricRevenue: "Revenue",
    metricOrders: "Orders",
    metricVisits: "Visits",
    metricCustomers: "Customers",
    metricAbandonment: "Abandonment",
    growthLabel: "Growth:",
    avgValueLabel: "Avg Value:",
    conversionLabel: "Conversion:",
    retentionLabel: "Retention:",
    inStockLabel: "In Stock:",
    topProducts: "Top Products",
    rankHeader: "Rank",
    productHeader: "Product",
    salesHeader: "Sales",
    revenueHeader: "Revenue",
    soldCount: "{count} sold",
    recentOrders: "Recent Orders",
    customerHeader: "Customer",
    amountHeader: "Amount",
    statusHeader: "Status",
    dateHeader: "Date",
    unitsCount: "{count} units",
    exportPdf: "Export PDF",
    productsRunningLow: "{count} product(s) running low",
    productHeader2: "Product",
    stockHeader2: "Stock",
    statusHeader2: "Status",
    outOfStock: "Out of Stock",
    criticalBadge: "Critical",
    lowBadge: "Low",
    recentActivity: "Recent Activity",
    viewAll: "View All",
    noRecentOrders: "No recent orders",
    minsAgo: "{mins}m ago",
    hoursAgo: "{hours}h ago",
    notifications: "Notifications",
    noNotifications: "All clear, no new notifications",
    viewAllOrders: "View All Orders",
    seedConfirm: "Are you sure? This will delete all current products and import luxury travel packages.",
    seedFailed: "Failed to seed travel packages.",
    seedError: "Something went wrong while importing travel data.",
    transformTourism: "Transform into a Real Tourism & Travel Website",
    transformDesc: "Import gorgeous ready-to-use luxury travel packages with destinations, pricing, and descriptions.",
    seedingLabel: "Seeding Destinations...",
    importedSuccess: "Imported Successfully!",
    importPackages: "Import Travel Packages",
    experienceJourney: "Experience Customer Journey",
    specialDrop: "Special Drop",
    limitedAvailability: "Limited Availability",
    limitedTimeDrops: "Limited Time Drops",
    shopSale: "Shop the sale",
    whatLookingFor: "WHAT ARE YOU LOOKING FOR?",
    popularCategories: "Popular Categories",
    newArrivals: "New Arrivals",
    limitedEditions: "Limited Editions",
    liveSuggestions: "Live Suggestions",
    startTyping: "Start typing to see magic...",
    addVideos: "Add videos to this gallery",
    videoMissing: "Video Missing",
    whatsappTitle: "WhatsApp Support",
    ourPackagesOffers: "Our Packages & Offers",
    packagesSubtitle: "Select the perfect plan designed to meet your specific needs.",
    perMonth: "/Month",
    selectPackage: "Select Package",
    realExperiences: "Real experiences from real people",
    thankYouTitle: "Thank You!",
    reviewSubmitted: "Your review has been submitted and will appear shortly.",
    writeAnotherReview: "Write Another Review",
    shareExperience: "Share Your Experience",
    yourRating: "Your Rating",
    yourNameRequired: "Your Name *",
    namePlaceholder2: "John Smith",
    roleCompany: "Role / Company (optional)",
    rolePlaceholder2: "CEO, Acme Corp",
    yourReview: "Your Review *",
    reviewPlaceholder2: "Tell us about your experience...",
    textEngine: "Text Engine",
    contentLabel: "Content",
    enterText: "Enter text...",
    fontFamily: "Font Family",
    inheritFont: "Inherit",
    thinFont: "Thin",
    lightFont: "Light",
    normalFont: "Normal",
    mediumFont: "Medium",
    semiBold: "Semi-Bold",
    boldFont: "Bold",
    blackFont: "Black",
    normalStyle: "NORMAL",
    italicStyle: "ITALIC",
    textColorFont: "Text Color",
    background: "Background",
    clearBtn: "Clear",
    boxPadding: "Box Padding",
    boxPaddingHelp: "Controls space inside the background box",
    cornerRadius: "Corner Radius",
    alignment: "Alignment",
    shadowEffects: "Shadow Effects",
    noneShadow: "None",
    softShadow: "Soft",
    hardShadow: "Hard",
    glowShadow: "Glow",
    neonShadow: "Neon",
    deepShadow: "Deep",
    dragPosition: "Drag Position",
    resetBtn: "Reset",
    saveAllStyles: "Save All Styles",
    failedSaveDB: "Failed to save to database:",
    networkError: "Network error while saving:",
    desktopView: "Desktop View",
    mobileView: "Mobile View",
    exitEditor: "Exit Editor",
    dashboardLink: "Dashboard",
    fullBuilder: "Full Builder",
    newButton: "New Button",
    addElement: "Add Element",
    addNewElement: "Add New Element",
    addActionButton: "Add Action Button",
    manageButtons: "Manage Buttons",
    imageBlocksComing: "Image Blocks (Coming)",
    textBlocksComing: "Text Blocks (Coming)",
    stylesPosition: "Styles & Position",
    textLabel: "Text",
    urlLabel: "URL",
    fontSize: "Font Size",
    roundness: "Roundness",
    maxLabel: "Max",
    bgColor: "BG Color",
    fontStyle: "Font Style",
    sansFont: "sans",
    serifFont: "serif",
    monoFont: "mono",
    saveBtn: "Save",
    deleteButtonConfirm: "Delete this button?",
    editButton: "Edit Button",
    editImage: "Edit Image",
    buttonText: "Button Text",
    buttonTextPlaceholder: "e.g. Shop Now",
    buttonLink: "Button Link (URL)",
    buttonLinkPlaceholder: "/store/...",
    currentImage: "Current Image",
    previewAlt: "Preview",
    changeImage: "Change Image",
    saveChangesBtn: "Save Changes",
    imageLibrary: "Media Library",
    imageLibraryDesc: "Choose an image or upload a new one",
    uploadNew: "UPLOAD NEW",
    loadingMedia: "Loading your media...",
    noImagesYet: "No images yet",
    noImagesDesc: "Upload your first image to the dashboard",
    mediaTip: "Tip: You can upload more images in the Dashboard > Media section.",
    cancel: "Cancel",
    selectImage: "Select Image",
    mobilePreview: "Mobile Preview",
    mobilePreviewHelp: "Mobile Preview Mode - Links within the frame will stay in mobile view.",
    theSignatureCollection: "THE SIGNATURE COLLECTION",
    viewArchive: "VIEW ARCHIVE",
    seasonalCampaign: "SEASONAL CAMPAIGN",
    signatureWatermark: "SIGNATURE",
    elevatingLifestyle: "Elevating your lifestyle through exceptional design and unparalleled quality.",
    immersiveExperience: "IMMERSIVE EXPERIENCE",
    cinemaView: "Cinema View",
    specialOffers: "Special Offers",
    limitedOffers: "Limited Offers",
    noActiveSales: "No active sales at the moment.",
    productSpotlight: "Product Spotlight",
    addBannersAdmin: "Add banners in the admin dashboard to display them here.",
    newDrops: "New Drops",
    viewAllLink: "View All",
    exploreCollectionsLink: "Explore Collections",
    establishedYear: "ESTABLISHED 2026",
    premiumItem: "just purchased a premium item",
    scrollToBegin: "Scroll to begin",
    theCollections: "THE COLLECTIONS",
    curatedSeries: "Curated Series",
    exploreLabel: "EXPLORE",
    viewCatalog: "VIEW CATALOG",
    voices: "VOICES",
    beyondLuxury: "BEYOND LUXURY",
    exploreArchive: "EXPLORE ARCHIVE",
    startDiscovery: "START DISCOVERY",
    campaignNo1: "CAMPAIGN NO. 1",
    abstractEssence: "ABSTRACT ESSENCE",
    zenithPhilosophy: "The Zenith Philosophy",
    zenithVoid: "ZENITH / VOID",
    noSectionsDeployed: "No sections deployed to home matrix.",
    theDrop: "THE DROP",
    latestArrivals: "LATEST ARRIVALS",
    viewAllProducts: "VIEW ALL PRODUCTS",
    excellenceInDetail: "EXCELLENCE IN EVERY DETAIL.",
    voicesOfExcellence: "Voices of Excellence",
    whoWeAre: "WHO WE ARE",
    premiumMaterials: "Premium Materials Only",
    limitedEditionReleases: "Limited Edition Releases",
    userAccount: "User account",
    userAlt: "User",
    changeLanguage: "Change Language",
    englishLabel: "English",
    searchPlaceholder: "Search...",
    emailNow: "Email now :",
    savePercentOff: "Save 50% off cosmetic beauty discount",
    usdCurrency: "USD $",
    englishLang: "ENGLISH",
    cartLabel: "Cart",
    zeroPrice: "$0.00",
    homeLink: "Home",
    packagesLink: "Packages",
    aboutUsLink: "About Us",
    storeLogoAlt: "Store",
    loginLink: "Login",
    instagramLabel: "Instagram",
    twitterLabel: "Twitter",
    facebookLabel: "Facebook",
    pinterestLabel: "Pinterest",
    discordLabel: "Discord",
    linksSection: "Links",
    inprint: "Inprint",
    privacy: "Privacy",
    contact: "Contact",
    social: "Social",
    builtBy: "Built by Antigravity",
    shopAndLearn: "Shop and Learn",
    storeLink: "Store",
    macLink: "Mac",
    iPadLink: "iPad",
    iPhoneLink: "iPhone",
    accountSection: "Account",
    manageYourID: "Manage Your ID",
    storeAccount: "Store Account",
    iCloudLink: "iCloud.com",
    forBusiness: "For Business",
    shopForBusiness: "Shop for Business",
    salesAndRefunds: "Sales and Refunds",
    navigate: "Navigate",
    seriesLink: "Series",
    manifesto: "Manifesto",
    journal: "Journal",
    supportSection: "Support",
    shippingLink: "Shipping",
    returnsLink: "Returns",
    helpLink: "Help",
    rawMaterials: "RAW MATERIALS",
    maximumImpact: "MAXIMUM IMPACT",

    unknown: "Unknown",

    // Templates
    storeTemplates: "Store Templates",
    selectLookFeel: "Select the look and feel of your storefront.",
    superAdminMode: "Super Admin Mode",
    hiddenFromUsers: "Hidden from Users",
    activeBadge: "ACTIVE",
    applyTemplate: "Apply Template",
    templateId: "Template ID:",
    confirmDeleteTemplate: "Are you sure you want to delete this template forever? This action cannot be undone.",
    abortMission: "Abort Mission",
    account: "Account",
    addColorPlaceholder: "Add color (e.g. Red)",
    addFeature: "Add Feature",
    addVideosToThisGallery: "Add videos to this gallery",
    allStatuses: "All Statuses",
    assetIdentity: "Asset Identity",
    black: "Black",
    bold: "Bold",
    deep: "Deep",
    glow: "Glow",
    hard: "Hard",
    neon: "Neon",
    soft: "Soft",
    boundaryPushingDesign: "Boundary-Pushing Design",
    builtByAntigravity: "Built by Antigravity",
    buttonLinkURL: "Button Link URL",
    cancelled: "Cancelled",
    captureAsset: "Capture Asset",
    chooseImageOrUpload: "Choose an image or upload a new one",
    clear: "Clear",
    content: "Content",
    controlProductEco: "Control your product ecosystem with precision",
    controlsSpaceInsideBackgroundBox: "Controls space inside the background box",
    dashboard: "Dashboard",
    deleteThisButton: "Delete this button?",
    delivered: "Delivered",
    deploymentStatus: "Deployment Status",
    describeEssencePlaceholder: "Describe the essence of this product...",
    discord: "Discord",
    draftStatus: "Draft",
    egShopNow: "e.g. Shop Now",
    egHyperLightSneakers: "e.g. Hyper-Light Sneakers",
    exploreCollection: "Explore Collection",
    facebook: "Facebook",
    failedToSaveToDatabase: "Failed to save to database",
    featurePlaceholder: "Feature...",
    handcraftedWithPremiumMaterials: "Handcrafted with premium materials",
    help: "Help",
    iCloudCom: "iCloud.com",
    inherit: "Inherit",
    initiateNewAsset: "Initiate New Asset",
    injectColor: "+ Add Color",
    injectSize: "+ Add Size",
    instagram: "Instagram",
    inventory: "Inventory",
    iPad: "iPad",
    iPhone: "iPhone",
    italic: "Italic",
    light: "Light",
    links: "Links",
    loadingYourMedia: "Loading your media...",
    mac: "Mac",
    marketSector: "Market Sector",
    max: "Max",
    mediaLibrary: "Media Library",
    medium: "Medium",
    mobilePreviewMode: "Mobile Preview Mode",
    modifyIdentity: "Modify Identity",
    na: "N/A",
    networkErrorWhileSaving: "Network error while saving",
    noAssetsDeployed: "No Assets Deployed",
    noFeaturesAdded: "No features added",
    none: "None",
    normal: "Normal",
    noSectorsDefined: "No sectors defined",
    packageFeaturesSpecs: "Package Features & Specs",
    pending: "Pending",
    pinterest: "Pinterest",
    preview: "Preview",
    reset: "Reset",
    returns: "Returns",
    sale: "Sale",
    save: "Save",
    sector: "Sector",
    series: "Series",
    shipped: "Shipped",
    shipping: "Shipping",
    shopTheSale: "Shop the Sale",
    startTypingToSeeMagic: "Start typing to see magic...",
    status: "Status",
    stock: "Stock",
    stockUnits: "Stock Units",
    store: "Store",
    storeSlashPlaceholder: "/store/...",
    studyInFormAndFunction: "A study in form and function",
    stylesAndPosition: "Styles & Position",
    support: "Support",
    syncMatrix: "Sync Matrix",
    termsOfUse: "Terms of Use",
    text: "Text",
    textColor: "Text Color",
    theSyndicate: "The Syndicate",
    theZenithCollection: "The Zenith Collection",
    thin: "Thin",
    tipUploadMoreImages: "Tip: You can upload more images in the Dashboard > Media section.",
    twitter: "Twitter",
    units: "Units",
    uploadFirstImage: "Upload your first image",
    url: "URL",
    valuation: "Valuation",
    valuePlaceholder: "Value...",
    variants: "Variants",
    vaultEmpty: "Vault is empty",
    viewSeries: "View Series",
    visualLink: "Visual Link",
    visualNode: "Visual Node",
    whatAreYouLookingFor: "What are you looking for?"
  },
  ar: {
    home: "الرئيسية",
    shop: "المتجر",
    shopAll: "تسوق الكل",
    myAccount: "حسابي",
    adminPanel: "لوحة التحكم",
    signOut: "تسجيل الخروج",
    signIn: "تسجيل الدخول",
    createAccount: "إنشاء حساب",
    
    // Storefront General
    addToCart: "إضافة للسلة",
    cart: "السلة",
    featuredProducts: "منتجات مميزة",
    exploreCollections: "استكشف المجموعات",
    saleOffers: "عروض التخفيضات",
    testimonials: "آراء العملاء",
    videoSection: "فيديو",
    marquee: "شريط الإعلانات",
    aboutUs: "من نحن",
    reviews: "التقييمات",

    // Admin Sidebar
    overview: "الرئيسية",
    products: "المنتجات",
    orders: "الطلبات",
    mediaHub: "مكتبة الوسائط",
    banners: "البانرات",
    storeBuilder: "مطور المتجر",
    siteBuilder: "مطور الموقع",
    generalSettings: "الإعدادات العامة",
    siteSettings: "إعدادات الموقع",
    platformStores: "متاجر المنصة",
    templates: "القوالب",
    customers: "العملاء",
    toursPackages: "البرامج السياحية",
    bookingInquiries: "استفسارات الحجز",
    bannersSliders: "البانرات والشرائح",
    mainControl: "التحكم الرئيسي",
    systemAdmin: "إدارة النظام",
    customization: "التخصيص",

    // Admin settings tabs and headers
    general: "عام",
    theme: "الألوان والمظهر",
    header: "رأس الصفحة والتنقل",
    signature: "ميزات متقدمة",
    tracking: "أكواد التتبع والبيكسل",
    business: "الشحن والتوصيل",
    storeCore: "نواة المتجر",
    masterControl: "التحكم الكامل في الهوية البصرية وشعار العلامة التجارية.",
    brandMatrix: "مصفوفة العلامة التجارية",
    marketIdentity: "اسم المتجر (العنوان)",
    enterStoreName: "أدخل اسم المتجر",
    seoSignal: "وصف المتجر (SEO)",
    premiumExperience: "تجربة تسوق فريدة ومميزة...",
    signatureLogo: "شعار الهيدر الرئيسي",
    browserNode: "أيقونة المتصفح (Favicon)",
    saveChanges: "حفظ التغييرات",
    saving: "جاري الحفظ...",
    settingsSaved: "تم حفظ الإعدادات بنجاح",
    themeConfiguration: "تهيئة المظهر واللون",
    primaryColor: "اللون الأساسي المميز",
    logoUpload: "رفع الشعار",
    navigationMenu: "قائمة التصفح الرئيسية",
    logisticsGrids: "خيارات وتكلفة الشحن",
    defineGrid: "تحديد المنطقة",
    zoneIdentifier: "معرف منطقة الشحن",
    rateValue: "قيمة التكلفة",
    livePulse: "تنبيهات حية للمبيعات",
    pulseInterval: "معدل التكرار (بالثواني)",
    socialProof: "آراء وتقييمات العملاء",
    injectReview: "إضافة تقييم جديد",
    identity: "اسم العميل",
    coordinates: "البلد أو المدينة",
    reviewContent: "محتوى التقييم",

    // Comm Channels (General Settings)
    commChannels: "قنوات التواصل",
    uplinkEmail: "بريد التواصل",
    voiceDirect: "رقم الهاتف المباشر",
    secureWhatsapp: "رقم الواتساب الفعال",
    faviconSpec: "المقاس القياسي المقترح: 32x32 أو 64x64 بكسل.",

    // Header topology (Header tab)
    headerTopology: "تنسيق الهيدر العلوي",
    navigationNodes: "روابط قائمة التنقل",
    injectLink: "+ إضافة رابط جديد",
    label: "اسم الرابط",
    uplinkPath: "مسار الرابط (الرابط)",
    
    // Header Layouts
    legacyLayout: "التقليدي",
    legacyLayoutDesc: "التنسيق الكلاسيكي القديم لمتجرك.",
    symmetricLayout: "المتوازن",
    symmetricLayoutDesc: "الشعار في اليسار، وروابط التنقل في المنتصف.",
    focusLayout: "المركّز",
    focusLayoutDesc: "الروابط في اليسار، الشعار في المنتصف.",
    discreteLayout: "المبسط",
    discreteLayoutDesc: "مظهر بسيط يركز على إجراءات العميل.",
    luxuryLayout: "الفاخر",
    luxuryLayoutDesc: "تصميم متدرج فاخر لعلامتك التجارية.",
    fluidLayout: "الديناميكي",
    fluidLayoutDesc: "تنسيق متجاوب بالكامل مخصص للهواتف أولاً.",

    // Color Architecture (Theme tab)
    colorArchitecture: "هندسة الألوان",
    colorArchitectureDesc: "حدد هوية الألوان الخاصة بمتجرك لجميع الصفحات والمكونات.",
    aestheticSynthesis: "محرك دمج الألوان",
    globalColorControl: "التحكم الكامل بألوان المتجر والمظهر البصري",
    versionActive: "النسخة الرابعة نشطة",
    phaseA: "اللون الأساسي",
    phaseB: "اللون الثانوي",
    flowPattern: "نمط تدرج الألوان",
    linearVertical: "خطي (عمودي)",
    linearHorizontal: "خطي (أفقي)",
    diagonalFlow: "تدرج قطري",
    radialCore: "شعاعي مركزي",
    injectionNode: "مكان تطبيق التدرج",
    globalFullMesh: "كامل الموقع",
    nexusHome: "الصفحة الرئيسية فقط",
    baseFooter: "تذييل الصفحة (الفوتر)",
    archiveShop: "صفحة المنتجات",
    neuralCategories: "صفحة الفئات",
    signalProduct: "تفاصيل المنتج",
    gatewayCart: "سلة المشتريات",
    secureCheckout: "صفحة الدفع الآمن",
    targetStream: "العنصر المستهدف",
    atmosphereBg: "خلفية الصفحة",
    frequencyText: "لون النصوص الرئيسي",
    kineticMotion: "الحركة والتأثيرات",
    static: "ثابت",
    animated: "متحرك وتفاعلي",
    applySynthesis: "تطبيق التنسيق والألوان",
    syncToCloud: "مزامنة البيانات سحابياً",
    homePageLabel: "الصفحة الرئيسية",
    homePageDesc: "الواجهة الأساسية والإنطباع الأول للعميل.",
    productGalleryLabel: "معرض المنتجات",
    collectionsDesc: "تصفح الأقسام واكتشاف المنتجات.",
    productDetailsLabel: "تفاصيل المنتج",
    productDetailsDesc: "صفحة عرض وتفاصيل المنتج الفردي.",
    shoppingCartLabel: "سلة التسوق",
    shoppingCartDesc: "مراجعة وإدارة السلة.",
    checkoutPhaseLabel: "مرحلة الدفع",
    checkoutPhaseDesc: "إتمام المعاملة والدفع الآمن.",
    globalSignalFooter: "التحكم الشامل وتذييل الصفحة",
    primaryBrandIdentity: "اللون الأساسي للعلامة التجارية",
    footerAtmosphereBg: "خلفية تذييل الصفحة",
    footerSignalText: "نص تذييل الصفحة",

    // Financial Signal
    financialSignalMatrix: "مصفوفة التحكم المالي والأسعار",
    priceDynamicsControl: "ديناميكيات الأسعار والتحكم بالعروض",
    economyModule: "وحدة الاقتصاد والمالية",
    corePriceSignal: "السعر الأساسي (الافتراضي)",
    standardRateColor: "لون السعر القياسي",
    pulseSignalSale: "السعر المخفض (العرض)",
    discountPulseColor: "لون سعر الخصم",

    // Tracking
    observatoryPixels: "وحدات بكسل التتبع والتحليل",
    metaPixel: "بكسل ميتا (فيسبوك)",
    tiktokSignal: "إشارات تيك توك",
    snapProtocol: "سناب شات",
    analyticsG4: "تحليلات جوجل (GA4)",
    secretId: "معرف بكسل التتبع (ID)",

    // Protocol messages
    protocolSecured: "تم حفظ الإعدادات بنجاح",
    uplinkPending: "بانتظار الحفظ والرفع",

    // Dashboard
    websiteAnalytics: "تحليلات الموقع",
    analyticsDashboard: "لوحة التحليلات",
    websiteAnalyticsDesc: "نظرة شاملة على موقعك الاستعراضي واستفسارات الحجز.",
    analyticsDashboardDesc: "نظرة شاملة على الأداء الرقمي لمتجرك.",
    inquiryLeads: "الاستفسارات المحتملة",
    totalRevenue: "إجمالي الإيرادات",
    uniqueLeads: "زوار فريدون",
    responseRate: "معدل الاستجابة",
    vsLastMonth: "مقارنة بالشهر الماضي",
    pageVisits: "زيارات الصفحة",
    totalOrders: "إجمالي الطلبات",
    conversionRate: "معدل التحويل",
    trafficSource: "مصدر الزيارات",
    avgValue: "متوسط القيمة",
    activePackages: "الباقات النشطة",
    inStock: "متوفر في المخزن",
    showcaseLive: "العرض المباشر",
    needsAttention: "يحتاج للاهتمام",
    tourismTemplate: "قالب السياحة",
    activeProducts: "المنتجات النشطة",
    leadsFunnel: "قمع الاستفسارات",
    salesFunnel: "المبيعات",
    websiteVisits: "زيارات الموقع",
    addToCartLabel: "إضافة للسلة",
    packageClicks: "نقرات الباقات",
    checkoutLabel: "الدفع",
    inquiriesSubmitted: "الاستفسارات المقدمة",
    purchasedLabel: "المشتريات",
    goalLabel: "الهدف",
    popularPackages: "الباقات الشائعة",
    bestSellers: "الأكثر مبيعاً",
    inquiriesReceived: "الاستفسارات المستلمة",
    unitsSold: "الوحدات المباعة",
    inquiryActivity: "نشاط الاستفسارات",
    activityHeatmap: "خريطة النشاط",

    // Dashboard extras
    organicDirect: "مباشر / طبيعي",
    active: "نشط",
    monthlyRevenueTrend: "اتجاه الإيرادات الشهري",
    live: "مباشر",
    daysOfWeek: "الأحد,الإثنين,الثلاثاء,الأربعاء,الخميس,الجمعة,السبت",
    at: "عند",
    on: "في يوم",

    // Products / Assets
    inventoryVault: "المخزون",
    controlProductPrecision: "تحكم في نظام المنتجات الخاص بك بدقة.",
    addNewAsset: "إضافة منتج جديد",
    physicalAsset: "أصل مادي",
    servicePackage: "خدمة / باقة",
    assetDesignation: "تسمية الأصل",
    assetNarrative: "وصف الأصل",
    baseValuation: "التقييم الأساسي ($)",
    flashDiscount: "خصم فوري ($)",
    dimensionScale: "مقياس الأبعاد",
    universalScale: "المقياس العالمي",
    colorSpectrum: "طيف الألوان",
    addSizePlaceholder: "إضافة حجم (مثال XL, 42)...",
    add: "إضافة",
    confirmDeleteProduct: "هل أنت متأكد من حذف هذا المنتج؟",

    // Banners
    motionCanvas: "لوحة الحركة",
    curateVisualNarrative: "نظم القصة البصرية المؤثرة لمتجرك.",
    sliderDynamics: "ديناميكيات الشريط المتحرك",
    globalTransitionProtocols: "السلوك العام وبروتوكولات الانتقال.",
    autoCycle: "دورة تلقائية",
    latencyMs: "الكمون (ملي ثانية)",
    morphEffect: "تأثير التحول",
    uiControls: "عناصر تحكم واجهة المستخدم",
    tactileArrows: "أسهم ملموسة",
    progressMap: "خريطة التقدم",
    visualNodes: "العقد البصرية",
    frameInventory: "مخزون الإطارات",
    appendFrame: "إضافة إطار",
    noMediaProjected: "لا يوجد وسائط معروضة",
    initializeCinematicFrame: "قم بتهيئة إطارك السينمائي الأول لإنشاء حضور متجرك.",
    launchSequence: "تسلسل الإطلاق",
    frame: "إطار",
    productionStatus: "حالة الإنتاج",
    mainDistribution: "التوزيع الرئيسي (16:9)",
    mobileNode: "عقدة الموبايل (9:16)",
    manifestTitle: "عنوان البيان",
    supportingNarrative: "نص مساعد",
    triggerText: "نص الزر",
    deploymentUrl: "رابط النشر",
    renderActionUi: "عرض واجهة الحدث",
    spatialPosition: "الموضع المكاني",
    visualArchitecture: "البنية المرئية",
    spatialContext: "السياق المكاني",
    definePreciseGeographicalCoordinates: "تحديد الإحداثيات الجغرافية الدقيقة لهذا الإطار ضمن متجرك.",
    commitToRegistry: "حفظ السجل",

    // Categories
    collectionHub: "مركز المجموعات",
    architectNavStructure: "صمم الهيكل الملاحي لمتجرك.",
    syncSuccessful: "تمت المزامنة بنجاح",
    commitChanges: "حفظ التغييرات",
    newCollection: "مجموعة جديدة",
    visualMatrix: "المصفوفة المرئية",
    defineStorefrontAesthetic: "حدد جمالية واجهة متجرك.",
    landingPage: "الصفحة المقصودة",
    allCollections: "كل المجموعات",
    modifySector: "تعديل القطاع",
    registerNewSector: "تسجيل قطاع جديد",
    sectorDesignation: "تسمية القطاع",
    narrativeDescription: "الوصف السردي",
    structuralHierarchy: "التسلسل الهرمي الهيكلي",
    visualSignature: "التوقيع البصري",
    collectionIdentity: "هوية المجموعة",
    registryCode: "رمز السجل",
    operations: "العمليات",
    confirmDeleteCategory: "هل أنت متأكد من حذف هذا القسم؟",

    // Orders
    orderStream: "الطلبات",
    realtimeTransactionMatrix: "مصفوفة المعاملات في الوقت الفعلي والتحكم في التنفيذ.",
    scanningMatrix: "جاري فحص المصفوفة...",
    activeRecords: "سجلات نشطة",
    noActiveTransactions: "لا توجد معاملات نشطة",
    node: "العقدة",
    revenue: "الإيرادات",
    matrixUnits: "العدد",
    timeStamp: "الطابع الزمني",
    statusLabel: "الحالة",
    verified: "مؤكد",
    loadMoreOrders: "تحميل المزيد من الطلبات",
    syncingNextNode: "جاري مزامنة العقدة التالية...",
    orderAnalysis: "تحليل الطلب",
    uplink: "الرابط الصاعد",
    awaitingSelection: "في انتظار الاختيار",
    clickTransactionNode: "انقر فوق عقدة معاملة لبدء التحليل والتنفيذ المفصل.",
    identityLogistics: "الهوية واللوجستيات",
    subject: "الموضوع",
    deliveryCoordinates: "إحداثيات التسليم",
    noCoordinatesProvided: "لم يتم توفير إحداثيات",
    commChannel: "قناة التواصل",
    productMatrix: "مصفوفة المنتجات",
    customerIntelligence: "ملاحظات / استخبارات العملاء",
    accumulatedTotal: "الإجمالي المتراكم",
    protocolExecution: "تنفيذ البروتوكول",

    // Colors
    advancedColorControls: "عناصر تحكم متقدمة بالألوان",
    controlColorAspect: "تحكم في كل جانب من جوانب الألوان لكل قالب.",
    primaryAccentColor: "اللون المميز الأساسي",
    mainBackground: "الخلفية الرئيسية",
    mainTextColor: "لون النص الرئيسي",
    headerBackgroundLabel: "خلفية الترويسة",
    headerTextLabel: "نص الترويسة",
    footerBackgroundLabel: "خلفية التذييل",
    footerTextLabel: "نص التذييل",
    primaryButtonBackground: "خلفية الزر الرئيسي",
    primaryButtonText: "نص الزر الرئيسي",
    priceTextColor: "لون نص السعر",
    salePriceColorLabel: "لون سعر التخفيض",
    saveColors: "حفظ الألوان",
    colorsSavedSuccessfully: "تم حفظ الألوان بنجاح!",
    failedToSaveColors: "فشل حفظ الألوان. يرجى المحاولة مرة أخرى.",

    // Media
    assetVault: "خزينة الأصول",
    centralizedRepository: "مستودع مركزي للموارد المرئية لمتجرك.",
    items: "عناصر",
    activeResourceInventory: "مخزون الموارد النشطة",
    newDeployment: "نشر جديد",
    initializeAsset: "تهيئة أصل",
    registerNewResource: "تسجيل مورد جديد في الخزينة",
    sourceProtocolUrl: "بروتوكول المصدر (رابط)",
    directLinkExternal: "رابط مباشر من عقدة توزيع خارجية.",
    abort: "إلغاء",
    deployAsset: "نشر الأصل",
    nullOutput: "لا يوجد مخرجات",
    confirmDeleteAsset: "هل أنت متأكد من حذف هذا الأصل؟",
    zeroAssetsDetected: "تم اكتشاف صفر أصول",
    vaultCurrentlyEmpty: "الخزينة فارغة حالياً. قم بتهيئة نشر مورد جديد لبدء بناء مكتبتك المرئية.",
    startDeploymentSequence: "بدء تسلسل النشر",

    // Storefront
    buyNow: "اشتر الآن",
    processing: "جاري المعالجة...",
    soldOut: "نفد من المخزون",
    productDetails: "تفاصيل المنتج",
    colorSelection: "اختيار اللون",
    sizeLabel: "المقاس",
    sizeGuide: "دليل المقاسات",
    quantityLabel: "الكمية",
    securePayment: "دفع آمن",
    fastDelivery: "توصيل سريع",
    easyReturns: "إرجاع سهل",
    youMayAlsoLike: "قد يعجبك أيضاً",
    customerReviews: "تقييمات العملاء",
    writeReview: "اكتب تقييماً",
    submitReview: "إرسال التقييم",
    noReviewsYet: "لا توجد تقييمات بعد. كن أول من يقيم!",
    unitsAvailable: "وحدة متوفرة",
    yourCartIsEmpty: "سلتك فارغة",
    shoppingCart: "سلة التسوق",
    deliveryDetails: "تفاصيل التوصيل",
    paymentMethod: "طريقة الدفع",
    orderSummary: "الملخص",
    subtotal: "المجموع الفرعي",
    deliveryLabel: "التوصيل",
    complimentary: "مجاني",
    totalLabel: "المجموع",
    discountLabel: "الخصم",
    couponCode: "كود الخصم",
    applyCode: "تطبيق",
    couponPlaceholder: "كود الخصم",
    completePurchase: "إتمام الشراء",
    encryptedSecure: "مشفر وآمن",
    orderNotes: "ملاحظات الطلب (اختياري)",
    shippingAddress: "عنوان الشحن",
    fullName: "الاسم الكامل",
    emailAddress: "البريد الإلكتروني",
    phoneNumber: "رقم الهاتف",
    password: "كلمة المرور",
    loggedInAs: "مسجل الدخول كـ",
    orderHistory: "سجل الطلبات",
    noOrdersYet: "لا توجد طلبات بعد",
    startShopping: "ابدأ التسوق",
    orderNum: "طلب #",
    statusColon: "الحالة:",
    orderedOn: "تم الطلب في",
    totalAmountColon: "المبلغ الإجمالي",
    previousPage: "→ الصفحة السابقة",
    nextPage: "← الصفحة التالية",
    pageOf: "صفحة {page} من {total}",
    blog: "المدونة",
    backToBlog: "→ العودة للمدونة",
    noPostsYet: "لا توجد مقالات بعد.",
    readMore: "اقرأ",
    blogManager: "إدارة المدونة",
    managePosts: "إدارة مقالات المدونة.",
    newPost: "مقال جديد",
    cancelBtn: "إلغاء",
    createPost: "إنشاء مقال",
    titleField: "العنوان",
    slugField: "الرابط",
    excerptField: "المقدمة",
    contentHtml: "المحتوى (HTML)",
    imageField: "الصورة",
    publishPost: "نشر المقال",
    loadingLabel: "جاري التحميل...",
    publishedLabel: "منشور",
    draftLabel: "مسودة",
    deleteLabel: "حذف",
    wishlist: "المفضلة",
    wishlistEmpty: "المفضلة فارغة.",
    browseProducts: "تصفح المنتجات",
    viewProduct: "عرض المنتج",
    addToWishlist: "أضف للمفضلة",
    inYourWishlist: "في المفضلة",
    newsletter: "النشرة البريدية",
    subscribeBtn: "اشتراك",
    subscribing: "جاري الاشتراك...",
    thanksSubscribing: "شكراً للاشتراك!",
    subscribeText: "اشترك لتصلك أحدث العروض والحصرية.",
    contactUs: "اتصل بنا",
    clientService: "خدمة العملاء",
    houseMatters: "الشؤون العامة",
    shippingReturns: "الشحن والإرجاع",
    trackOrder: "تتبع الطلب",
    appointments: "المواعيد",
    sustainability: "الاستدامة",
    heritage: "الإرث",
    careers: "وظائف",
    termsOfService: "شروط الخدمة",
    privacyPolicy: "سياسة الخصوصية",
    storeNotFound: "المتجر غير موجود",
    storeNotFoundDesc: "المتجر المطلوب غير موجود في قاعدة البيانات.",
    allRightsReserved: "جميع الحقوق محفوظة.",

    // Templates
    storeTemplates: "قوالب المتجر",
    selectLookFeel: "حدد شكل ومظهر متجرك.",
    superAdminMode: "وضع المدير المتميز",
    hiddenFromUsers: "مخفي عن المستخدمين",
    activeBadge: "نشط",
    applyTemplate: "تطبيق القالب",
    templateId: "معرف القالب:",
    confirmDeleteTemplate: "هل أنت متأكد من حذف هذا القالب نهائياً؟ لا يمكن التراجع.",

    // Arabic translations for ALL missing storefront/component/admin keys
    welcomeStore: "مرحباً بك في متجرنا الرسمي.",
    exploreProducts: "استكشف المنتجات",
    storeSuspended: "المتجر معلق",
    suspendedDesc: "هذا المتجر قيد الصيانة حالياً أو تم تعطيله مؤقتاً من قبل مدير المنصة. يرجى المحاولة لاحقاً.",
    backToHome: "العودة للرئيسية",
    homeBreadcrumb: "الرئيسية",
    allItems: "كل المنتجات",
    sortBy: "ترتيب حسب:",
    featured: "مميز",
    priceLowHigh: "السعر: من الأقل للأعلى",
    priceHighLow: "السعر: من الأعلى للأقل",
    newest: "الأحدث",
    noProductsFound: "لا توجد منتجات",
    noProductsDesc: "لم نتمكن من العثور على منتجات في هذه المجموعة.",
    clearFilters: "مسح التصفية",
    saleBadge: "تخفيض",
    viewDetails: "عرض التفاصيل",
    allCollectionsTitle: "جميع المجموعات",
    allCollectionsDesc: "استكشف مجموعتنا الكاملة من الأساسيات الممتازة.",
    saleTitle: "تخفيضات",
    saleDesc: "منتجات ممتازة بقيمة استثنائية.",
    emptyCollection: "مجموعة فارغة",
    emptyCollectionDesc: "لم نتمكن من العثور على منتجات في هذا الاختيار.",
    exploreAll: "استكشف الكل",
    premiumTravelPackage: "باقة سفر ممتازة",
    curatedPackage: "باقة منسقة",
    privateGroupTours: "جولات خاصة أو جماعية",
    perTraveler: "/ لكل مسافر",
    bookThisTour: "احجز هذه الباقة",
    fullNamePlaceholder: "مثال: أحمد محمد",
    phonePlaceholder: "مثال: 201000000000+",
    departureDate: "تاريخ المغادرة التقريبي",
    numberOfTravelers: "عدد المسافرين",
    specialRequests: "طلبات خاصة أو ملاحظات",
    requestsPlaceholder: "حدد تفضيلات الفندق أو متطلبات الطعام أو المدة المخصصة.",
    submitting: "جارٍ إرسال الاستفسار...",
    sendBooking: "إرسال طلب الحجز",
    inquiryReceived: "تم استلام الاستفسار!",
    inquiryReceivedDesc: "تم تقديم طلب الحجز بنجاح. سنتواصل معك قريباً.",
    fullNameRequired: "الاسم الكامل ورقم الهاتف مطلوبان.",
    bookingFailed: "فشل إرسال طلب الحجز.",
    onlyLeft: "لم يتبق سوى {count} - اطلب قريباً!",
    maxStockReached: "تم الوصول للحد الأقصى من المخزون",
    addedViewCart: "أضيف! عرض السلة",
    unavailable: "غير متاح",
    selectColor: "اختر اللون",
    selectSize: "اختر المقاس",
    lowStock: "مخزون منخفض: {count} وحدة",
    inventoryAvailable: "المخزون متاح",
    addToBag: "أضف للحقيبة",
    globalShipping: "شحن عالمي",
    productGuarantee: "ضمان المنتج",
    saleOffer: "عرض التخفيض",
    cartEmptyDesc: "يبدو أنك لم تضف أي شيء إلى سلة التسوق بعد.",
    continueShopping: "متابعة التسوق",
    shippingCalc: "تحسب عند الدفع",
    proceedToCheckout: "متابعة الدفع",
    removeItemBtn: "إزالة",
    welcomeBack: "مرحباً بعودتك",
    signInToTrack: "سجل الدخول لتتبع طلباتك وإدارة حسابك.",
    forgotPassword: "نسيت كلمة المرور؟",
    noAccount: "ليس لديك حساب؟",
    registerNow: "سجل الآن",
    joinUs: "انضم إلينا لإدارة تجربة التسوق الخاصة بك",
    fullNameLabel: "الاسم الكامل",
    haveAccount: "لديك حساب بالفعل؟",
    signInLink: "تسجيل الدخول",
    searchResults: "نتائج البحث",
    showingResults: 'نتائج البحث عن "{query}"',
    searchPlaceholder2: "ابحث في متجرنا",
    searchDesc: "أدخل كلمة للبحث عن المنتجات.",
    noProductsMatch: 'لم نتمكن من العثور على منتجات تطابق "{query}".',
    browseAllProducts: "تصفح جميع المنتجات",
    ourCollections: "مجموعتنا",
    itemsCount: "{count} عنصر",
    productsCount: "{count} منتج",
    faqHeading: "الأسئلة الشائعة",
    faqDesc: "اعثر على إجابات للأسئلة الشائعة حول منتجاتنا والشحن والإرجاع.",
    stillQuestions: "لا يزال لديك أسئلة؟",
    stillQuestionsDesc: "فريق الدعم لدينا هنا للمساعدة.",
    contactSupport: "اتصل بالدعم",
    getInTouch: "تواصل معنا",
    getInTouchDesc: "يسعدنا سماع رأيك. تواصل مع فريقنا.",
    contactInfo: "معلومات الاتصال",
    ourStudio: "الاستوديو الخاص بنا",
    studioAddress: "123 شارع الفخامة، حي التصميم، القاهرة، مصر",
    emailUs: "راسلنا عبر البريد",
    supportEmail: "support@luxestore.com",
    callUs: "اتصل بنا",
    callHours: "من الاثنين إلى الجمعة 9ص - 6م",
    callPhone: "201025574570+",
    whatsappSupport: "دعم واتساب",
    whatsappDesc: "للحصول على أسرع رد، تواصل معنا عبر واتساب.",
    chatWhatsApp: "تواصل عبر واتساب",
    sendMessage: "أرسل لنا رسالة",
    sendMessageBtn: "إرسال الرسالة",
    shippingHeading: "الشحن والإرجاع",
    shippingDesc: "كل ما تحتاج معرفته عن سياسات الشحن والإرجاع.",
    shippingPolicy: "سياسة الشحن",
    domesticShipping: "الشحن المحلي (الولايات المتحدة)",
    internationalShipping: "الشحن الدولي",
    processingTime: "أوقات التجهيز",
    returnPolicy: "سياسة الإرجاع",
    howToReturn: "كيفية الإرجاع",
    orderConfirmed: "تم تأكيد الطلب",
    orderConfirmedDesc: "شكراً لك! ستتلقى بريداً إلكترونياً للتأكيد قريباً.",
    orderNumber: "رقم الطلب",
    verifyEmail: "تحقق من بريدك الإلكتروني",
    verifyDesc: "أدخل رمز التحقق المكون من 6 أرقام المرسل إلى بريدك",
    verifyBtn: "تحقق",
    verifiedRedirect: "تم التحقق! جارٍ إعادة التوجيه...",
    noEmailFound: "لم يتم العثور على البريد الإلكتروني.",
    enterFullCode: "يرجى إدخال الرمز المكون من 6 أرقام بالكامل.",
    loadingReviews: "جارٍ التحميل...",
    reviewThankYou: "شكراً لك على مراجعتك!",
    reviewPlaceholder: "شارك تجربتك (اختياري)",
    yourName: "اسمك",
    ratingLabel: "التقييم:",
    reviewSuccess: "تم إرسال المراجعة!",
    searchOrders: "ابحث عن الطلبات (الاسم، البريد، الهاتف، المعرف)...",
    searchOrdersPlaceholder: "ابحث عن الطلبات (الاسم، البريد، الهاتف، المعرف)...",
    productNamePlaceholder: "مثال: حذاء هايبر-لايت",
    productDescPlaceholder: "صف جوهر هذا المنتج...",
    nonePlaceholder: "لا شيء",
    unknownSector: "قطاع غير معروف",
    createCategoryFirst: "يرجى إنشاء قسم أولاً قبل إضافة المنتجات.",
    errorAddingProduct: "خطأ في إضافة المنتج",
    deleteProductConfirm: "هل أنت متأكد من حذف هذا المنتج؟",
    totalCustomers: "إجمالي العملاء",
    totalSpend: "إجمالي الإنفاق",
    totalSpendKpi: "مؤشر إجمالي الإنفاق",
    avgSpend: "متوسط الإنفاق",
    noCustomersYet: "لا يوجد عملاء بعد",
    noCustomersDesc: "بمجرد تقديم الطلبات، سيظهر العملاء هنا.",
    customerHead: "العميل",
    customerEmail: "البريد",
    customerPhone: "الهاتف",
    customerOrders: "الطلبات",
    customerTotal: "الإجمالي",
    lastOrder: "آخر طلب",
    registeredCustomers: "{count} عميل مسجل",
    postTitlePlaceholder: "عنوان المقال",
    postSlugPlaceholder: "رابط-المقال",
    excerptPlaceholder: "وصف مختصر",
    contentPlaceholder: "<p>محتوى مقالك هنا...</p>",
    savingLabel: "جارٍ الحفظ...",
    noPostsYetAdmin: "لا توجد مقالات بعد. أنشئ مقالك الأول.",
    deletePostConfirm: "حذف هذه المقالة؟",
    authorDefault: "مدير",
    bannerNew: "بانر جديد",
    bannerSubtitle: "أضف عنواناً فرعياً جذاباً هنا",
    bannerBtnText: "تسوق الآن",
    bannerBtnLink: "/products",
    uhdRecommended: "UHD موصى به",
    portraitOptimized: "مُحسَّن للصورة الرأسية",
    enterHeadline: "أدخل العنوان الرئيسي",
    defineVision: "حدد رؤية هذا الإطار...",
    manifestSync: "تمت مزامنة البيان",
    awaitingInstruction: "بانتظار التعليمات",
    alphaSynthesis: "التركيب ألفا",
    alphaSynthesisDesc: "إزالة الخلفية من شعار الرأس.",
    subjectName: "اسم الموضوع",
    sectorLocation: "القطاع / الموقع",
    inputSignal: "أدخل محتوى الإشارة...",
    deleteReview: "حذف المراجعة",
    placeholderGlobal: "مثال: عالمي",
    bentoGrid: "شبكة بينتو",
    bentoGridDesc: "فسيفساء سينمائية فاخرة",
    standardGrid: "شبكة قياسية",
    standardGridDesc: "تخطيط نظيف من 4 أعمدة",
    horizontalScroll: "تمرير أفقي",
    horizontalScrollDesc: "شريط دوار أنيق",
    minimalList: "قائمة بسيطة",
    minimalListDesc: "قائمة رأسية بسيطة",
    circleBubbles: "دوائر",
    circleBubblesDesc: "فقاعات بأسلوب عصري",
    categoryPlaceholder: "مثال: أساسيات الصيف",
    categoryDescPlaceholder: "اشرح موضوع هذه المجموعة...",
    rootCollection: "المجموعة الجذرية",
    updateRegistry: "تحديث السجل",
    initializeSector: "تهيئة القطاع",
    cancelBtn2: "إلغاء",
    nodeOf: "عقدة من",
    noMatrixData: "لا توجد بيانات",
    noMatrixDesc: "قم بتهيئة القطاع الأول لبدء النشر.",
    assetNamePlaceholder: "مثال: CORE_BANNER_ALPHA",
    assetUrlPlaceholder: "https://cdn.resource.com/...",
    noAssetsDetected: "لم يتم اكتشاف أصول",
    noAssetsDesc: "الخزنة فارغة حالياً. ابدأ نشر مورد جديد لبناء مكتبتك البصرية.",
    startDeployment: "بدء تسلسل النشر",
    hideFromUsers: "إخفاء عن المستخدمين",
    showToUsers: "إظهار للمستخدمين",
    deleteForever: "حذف نهائي",
    modernCommerce: "التجارة الحديثة",
    zenithLuxury: "زينيث الفاخرة",
    signatureBrand: "العلامة التجارية",
    searchStores: "ابحث بالمتجر أو الرابط أو المالك...",
    activeStatus: "نشط",
    suspendedStatus: "معلق",
    storeDesign: "تصميم المتجر",
    deactivateStore: "تعطيل",
    reactivateStore: "إعادة تفعيل",
    permanentlyDelete: "حذف المتجر نهائياً",
    confirmDeactivate: "هل أنت متأكد من تعطيل هذا المتجر؟",
    confirmPermanentDelete: "تحذير: هل أنت متأكد من حذف هذا المتجر نهائياً؟ لا يمكن التراجع!",
    noStoresFound: "لم يتم العثور على متاجر تطابق بحثك.",
    viewLiveStore: "عرض المتجر المباشر",
    addNewSection: "إضافة قسم جديد",
    noSectionSelected: "لم يتم تحديد قسم",
    noSectionDesc: "انقر على قسم من الشريط الجانبي لتحرير محتواه وتصميمه.",
    editContentStyle: "تحرير المحتوى والتصميم",
    saleSectionStyle: "نمط قسم التخفيضات",
    contentSettings: "إعدادات المحتوى",
    subtitleField: "العنوان الفرعي",
    sectionImage: "صورة القسم",
    tagline: "شعار",
    taglinePlaceholder: "من نحن",
    primaryDescription: "الوصف الرئيسي",
    secondaryDescription: "الوصف الثانوي",
    testimonialDefault: "خدمة ممتازة!",
    addNew: "+ إضافة جديد",
    namePlaceholder: "الاسم",
    rolePlaceholder: "الدور",
    testimonialPlaceholder: "محتوى الشهادة...",
    scrollingTexts: "نصوص متحركة",
    addText: "+ إضافة نص",
    storefrontSaved: "تم حفظ تخطيط المتجر!",
    welcomePlatform: "مرحباً بك في منصتنا",
    discoverServices: "اكتشف خدمات رائعة",
    whatClientsSay: "ماذا يقول عملاؤنا",
    whatCustomersSay: "ماذا يقول عملاؤنا",
    shopByCategory: "تسوق حسب القسم",
    trendingNow: "الأكثر رواجاً",
    newAnnouncement: "إعلان جديد",
    welcomeStoreTitle: "مرحباً بك في متجرنا",
    discoverProducts: "اكتشف منتجات رائعة",
    heroSection: "القسم الرئيسي",
    bannersSlider: "شريط البانرات",
    categoriesSection: "الأقسام",
    featuredProductsSection: "منتجات مميزة",
    aboutUsSection: "من نحن",
    testimonialsSection: "الشهادات",
    richText: "نص منسق",
    announcementMarquee: "شريط الإعلانات",
    websiteHero: "القسم الرئيسي",
    ourPackages: "باقاتنا",
    dateAllTime: "كل الوقت",
    dateToday: "اليوم",
    dateLast7: "آخر 7 أيام",
    dateThisMonth: "هذا الشهر",
    dateLastMonth: "الشهر الماضي",
    dateThisYear: "هذه السنة",
    analyticsReport: "تقرير التحليلات",
    generatedBy: "منشور بواسطة Shopora Analytics",
    keyMetrics: "المقاييس الرئيسية",
    metricHeader: "المقياس",
    valueHeader: "القيمة",
    detailHeader: "التفاصيل",
    metricRevenue: "الإيرادات",
    metricOrders: "الطلبات",
    metricVisits: "الزيارات",
    metricCustomers: "العملاء",
    metricAbandonment: "التخلي",
    growthLabel: "النمو:",
    avgValueLabel: "متوسط القيمة:",
    conversionLabel: "التحويل:",
    retentionLabel: "الاحتفاظ:",
    inStockLabel: "في المخزون:",
    topProducts: "أفضل المنتجات",
    rankHeader: "الترتيب",
    productHeader: "المنتج",
    salesHeader: "المبيعات",
    revenueHeader: "الإيرادات",
    soldCount: "{count} مباع",
    recentOrders: "الطلبات الأخيرة",
    customerHeader: "العميل",
    amountHeader: "المبلغ",
    statusHeader: "الحالة",
    dateHeader: "التاريخ",
    unitsCount: "{count} وحدة",
    exportPdf: "تصدير PDF",
    productsRunningLow: "{count} منتج(ة) مخزونها منخفض",
    productHeader2: "المنتج",
    stockHeader2: "المخزون",
    statusHeader2: "الحالة",
    outOfStock: "نفذ من المخزون",
    criticalBadge: "حرج",
    lowBadge: "منخفض",
    recentActivity: "النشاط الأخير",
    viewAll: "عرض الكل",
    noRecentOrders: "لا توجد طلبات حديثة",
    minsAgo: "منذ {mins} دقيقة",
    hoursAgo: "منذ {hours} ساعة",
    notifications: "الإشعارات",
    noNotifications: "كل شيء على ما يرام، لا توجد إشعارات",
    viewAllOrders: "عرض جميع الطلبات",
    seedConfirm: "هل أنت متأكد؟ سيتم حذف جميع المنتجات الحالية واستيراد باقات سفر فاخرة.",
    seedFailed: "فشل استيراد باقات السفر.",
    seedError: "حدث خطأ أثناء استيراد بيانات السفر.",
    transformTourism: "تحويل إلى موقع سياحة وسفر حقيقي",
    transformDesc: "استورد باقات سفر فاخرة جاهزة مع الوجهات والأسعار والأوصاف.",
    seedingLabel: "جارٍ استيراد الوجهات...",
    importedSuccess: "تم الاستيراد بنجاح!",
    importPackages: "استيراد باقات السفر",
    experienceJourney: "تجربة رحلة العميل",
    specialDrop: "إصدار خاص",
    limitedAvailability: "توفر محدود",
    limitedTimeDrops: "إصدارات محدودة الوقت",
    shopSale: "تسوق التخفيضات",
    whatLookingFor: "ماذا تبحث عنه؟",
    popularCategories: "الأقسام الشائعة",
    newArrivals: "الوصلات الجديدة",
    limitedEditions: "الإصدارات المحدودة",
    liveSuggestions: "اقتراحات حية",
    startTyping: "ابدأ الكتابة لترى النتائج...",
    addVideos: "أضف فيديوهات لهذه المعارض",
    videoMissing: "الفيديو مفقود",
    whatsappTitle: "دعم واتساب",
    ourPackagesOffers: "باقاتنا وعروضنا",
    packagesSubtitle: "اختر الخطة المثالية المصممة لتناسب احتياجاتك.",
    perMonth: "/شهر",
    selectPackage: "اختر الباقة",
    realExperiences: "تجارب حقيقية من أشخاص حقيقيين",
    thankYouTitle: "شكراً لك!",
    reviewSubmitted: "تم إرسال مراجعتك وستظهر قريباً.",
    writeAnotherReview: "كتابة مراجعة أخرى",
    shareExperience: "شارك تجربتك",
    yourRating: "تقييمك",
    yourNameRequired: "اسمك *",
    namePlaceholder2: "محمد أحمد",
    roleCompany: "الدور / الشركة (اختياري)",
    rolePlaceholder2: "رئيس تنفيذي، شركة أكما",
    yourReview: "مراجعتك *",
    reviewPlaceholder2: "أخبرنا عن تجربتك...",
    textEngine: "محرر النصوص",
    contentLabel: "المحتوى",
    enterText: "أدخل النص...",
    fontFamily: "نوع الخط",
    inheritFont: "افتراضي",
    thinFont: "رفيع",
    lightFont: "فاتح",
    normalFont: "عادي",
    mediumFont: "متوسط",
    semiBold: "نصف عريض",
    boldFont: "عريض",
    blackFont: "أسود",
    normalStyle: "عادي",
    italicStyle: "مائل",
    textColorFont: "لون النص",
    background: "الخلفية",
    clearBtn: "مسح",
    boxPadding: "الحشوة الداخلية",
    boxPaddingHelp: "التحكم في المسافة داخل مربع الخلفية",
    cornerRadius: "تدوير الزوايا",
    alignment: "المحاذاة",
    shadowEffects: "تأثيرات الظل",
    noneShadow: "بدون",
    softShadow: "ناعم",
    hardShadow: "قوي",
    glowShadow: "متوهج",
    neonShadow: "نيون",
    deepShadow: "عميق",
    dragPosition: "سحب الموقع",
    resetBtn: "إعادة ضبط",
    saveAllStyles: "حفظ جميع الأنماط",
    failedSaveDB: "فشل الحفظ في قاعدة البيانات:",
    networkError: "خطأ في الشبكة أثناء الحفظ:",
    desktopView: "عرض سطح المكتب",
    mobileView: "عرض الجوال",
    exitEditor: "خروج من المحرر",
    dashboardLink: "لوحة التحكم",
    fullBuilder: "المنشئ الكامل",
    newButton: "زر جديد",
    addElement: "إضافة عنصر",
    addNewElement: "إضافة عنصر جديد",
    addActionButton: "إضافة زر إجراء",
    manageButtons: "إدارة الأزرار",
    imageBlocksComing: "كتل الصور (قريباً)",
    textBlocksComing: "كتل النصوص (قريباً)",
    stylesPosition: "الأنماط والموضع",
    textLabel: "النص",
    urlLabel: "الرابط",
    fontSize: "حجم الخط",
    roundness: "الاستدارة",
    maxLabel: "الحد الأقصى",
    bgColor: "لون الخلفية",
    fontStyle: "نمط الخط",
    sansFont: "sans",
    serifFont: "serif",
    monoFont: "mono",
    saveBtn: "حفظ",
    deleteButtonConfirm: "حذف هذا الزر؟",
    editButton: "تحرير الزر",
    editImage: "تحرير الصورة",
    buttonText: "نص الزر",
    buttonTextPlaceholder: "مثال: تسوق الآن",
    buttonLink: "رابط الزر",
    buttonLinkPlaceholder: "/store/...",
    currentImage: "الصورة الحالية",
    previewAlt: "معاينة",
    changeImage: "تغيير الصورة",
    saveChangesBtn: "حفظ التغييرات",
    imageLibrary: "مكتبة الوسائط",
    imageLibraryDesc: "اختر صورة أو حمّل صورة جديدة",
    uploadNew: "رفع جديد",
    loadingMedia: "جارٍ تحميل الوسائط...",
    noImagesYet: "لا توجد صور بعد",
    noImagesDesc: "حمّل صورتك الأولى إلى لوحة التحكم",
    mediaTip: "نصيحة: يمكنك رفع المزيد من الصور في لوحة التحكم > الوسائط.",
    cancel: "إلغاء",
    selectImage: "اختر صورة",
    mobilePreview: "معاينة الجوال",
    mobilePreviewHelp: "وضع معاينة الجوال - ستبقى الروابط داخل الإطار في عرض الجوال.",
    theSignatureCollection: "مجموعة التوقيع",
    viewArchive: "عرض الأرشيف",
    seasonalCampaign: "حملة موسمية",
    signatureWatermark: "توقيع",
    elevatingLifestyle: "ارتقِ بأسلوب حياتك من خلال التصميم الاستثنائي والجودة التي لا تضاهى.",
    immersiveExperience: "تجربة غامرة",
    cinemaView: "عرض سينمائي",
    specialOffers: "عروض خاصة",
    limitedOffers: "عروض محدودة",
    noActiveSales: "لا توجد تخفيضات نشطة حالياً.",
    productSpotlight: "تسليط الضوء على المنتج",
    addBannersAdmin: "أضف بانرات في لوحة التحكم لعرضها هنا.",
    newDrops: "إصدارات جديدة",
    viewAllLink: "عرض الكل",
    exploreCollectionsLink: "استكشف المجموعات",
    establishedYear: "تأسست 2026",
    premiumItem: "اشترى للتو عنصراً ممتازاً",
    scrollToBegin: "اسحب للبدء",
    theCollections: "المجموعات",
    curatedSeries: "سلسلة منسقة",
    exploreLabel: "استكشف",
    viewCatalog: "عرض الكتالوج",
    voices: "آراء",
    beyondLuxury: "ما وراء الفخامة",
    exploreArchive: "استكشف الأرشيف",
    startDiscovery: "ابدأ الاكتشاف",
    campaignNo1: "الحملة رقم 1",
    abstractEssence: "الجوهر التجريدي",
    zenithPhilosophy: "فلسفة زينيث",
    zenithVoid: "زينيث / الفراغ",
    noSectionsDeployed: "لم يتم نشر أقسام في المصفوفة الرئيسية.",
    theDrop: "الإصدار",
    latestArrivals: "أحدث الوصلات",
    viewAllProducts: "عرض جميع المنتجات",
    excellenceInDetail: "التميز في كل التفاصيل.",
    voicesOfExcellence: "أصوات التميز",
    whoWeAre: "من نحن",
    premiumMaterials: "مواد ممتازة فقط",
    limitedEditionReleases: "إصدارات محدودة",
    userAccount: "حساب المستخدم",
    userAlt: "مستخدم",
    changeLanguage: "تغيير اللغة",
    englishLabel: "الإنجليزية",
    searchPlaceholder: "بحث...",
    emailNow: "البريد الآن:",
    savePercentOff: "وفر 50% على تخفيضات التجميل",
    usdCurrency: "دولار أمريكي $",
    englishLang: "الإنجليزية",
    cartLabel: "السلة",
    zeroPrice: "$0.00",
    homeLink: "الرئيسية",
    packagesLink: "الباقات",
    aboutUsLink: "من نحن",
    storeLogoAlt: "المتجر",
    loginLink: "تسجيل الدخول",
    instagramLabel: "انستغرام",
    twitterLabel: "تويتر",
    facebookLabel: "فيسبوك",
    pinterestLabel: "بينتريست",
    discordLabel: "ديسكورد",
    linksSection: "روابط",
    inprint: "مطبوعات",
    privacy: "الخصوصية",
    contact: "اتصال",
    social: "تواصل",
    builtBy: "بُني بواسطة Antigravity",
    shopAndLearn: "تسوق وتعلم",
    storeLink: "المتجر",
    macLink: "Mac",
    iPadLink: "iPad",
    iPhoneLink: "iPhone",
    accountSection: "الحساب",
    manageYourID: "إدارة معرفك",
    storeAccount: "حساب المتجر",
    iCloudLink: "icloud.com",
    forBusiness: "للأعمال",
    shopForBusiness: "تسوق للأعمال",
    salesAndRefunds: "المبيعات والاسترداد",
    navigate: "تصفح",
    seriesLink: "سلسلة",
    manifesto: "بيان",
    journal: "مجلة",
    supportSection: "الدعم",
    shippingLink: "الشحن",
    returnsLink: "الإرجاع",
    helpLink: "المساعدة",
    rawMaterials: "مواد خام",
    maximumImpact: "أقصى تأثير",
    abortMission: "إلغاء المهمة",
    account: "الحساب",
    addColorPlaceholder: "أضف لوناً (مثال: أحمر)",
    addFeature: "إضافة ميزة",
    addVideosToThisGallery: "أضف فيديوهات لهذا المعرض",
    allStatuses: "جميع الحالات",
    assetIdentity: "هوية الأصل",
    black: "أسود",
    bold: "عريض",
    deep: "عميق",
    glow: "متوهج",
    hard: "قوي",
    neon: "نيون",
    soft: "ناعم",
    boundaryPushingDesign: "تصميم يتخطى الحدود",
    builtByAntigravity: "بني بواسطة Antigravity",
    buttonLinkURL: "رابط الزر",
    cancelled: "ملغي",
    captureAsset: "التقاط الأصل",
    chooseImageOrUpload: "اختر صورة أو ارفع واحدة",
    clear: "مسح",
    content: "المحتوى",
    controlProductEco: "تحكم في نظام المنتجات بدقة",
    controlsSpaceInsideBackgroundBox: "التحكم في المسافة داخل مربع الخلفية",
    dashboard: "لوحة التحكم",
    deleteThisButton: "حذف هذا الزر؟",
    delivered: "تم التوصيل",
    deploymentStatus: "حالة النشر",
    describeEssencePlaceholder: "صف جوهر هذا المنتج...",
    discord: "ديسكورد",
    draftStatus: "مسودة",
    egShopNow: "مثال: تسوق الآن",
    egHyperLightSneakers: "مثال: حذاء هايبر-لايت",
    exploreCollection: "استكشف المجموعة",
    facebook: "فيسبوك",
    failedToSaveToDatabase: "فشل الحفظ في قاعدة البيانات",
    featurePlaceholder: "ميزة...",
    handcraftedWithPremiumMaterials: "مصنوع يدوياً بمواد ممتازة",
    help: "مساعدة",
    iCloudCom: "iCloud.com",
    inherit: "وراثة",
    initiateNewAsset: "بدء أصل جديد",
    injectColor: "+ إضافة لون",
    injectSize: "+ إضافة مقاس",
    instagram: "انستغرام",
    inventory: "المخزون",
    iPad: "iPad",
    iPhone: "iPhone",
    italic: "مائل",
    light: "فاتح",
    links: "روابط",
    loadingYourMedia: "جارٍ تحميل الوسائط...",
    mac: "Mac",
    marketSector: "قطاع السوق",
    max: "الحد الأقصى",
    mediaLibrary: "مكتبة الوسائط",
    medium: "متوسط",
    mobilePreviewMode: "وضع معاينة الجوال",
    modifyIdentity: "تعديل الهوية",
    na: "غير متاح",
    networkErrorWhileSaving: "خطأ في الشبكة أثناء الحفظ",
    noAssetsDeployed: "لم يتم نشر أصول",
    noFeaturesAdded: "لم تتم إضافة ميزات",
    none: "لا شيء",
    normal: "عادي",
    noSectorsDefined: "لم يتم تعريف قطاعات",
    packageFeaturesSpecs: "ميزات ومواصفات الباقة",
    pending: "قيد الانتظار",
    pinterest: "بينتريست",
    preview: "معاينة",
    reset: "إعادة ضبط",
    returns: "الإرجاع",
    sale: "تخفيضات",
    save: "حفظ",
    sector: "قطاع",
    series: "سلسلة",
    shipped: "تم الشحن",
    shipping: "الشحن",
    shopTheSale: "تسوق التخفيضات",
    startTypingToSeeMagic: "ابدأ الكتابة لترى النتائج...",
    status: "الحالة",
    stock: "المخزون",
    stockUnits: "وحدات المخزون",
    store: "المتجر",
    storeSlashPlaceholder: "/store/...",
    studyInFormAndFunction: "دراسة في الشكل والوظيفة",
    stylesAndPosition: "الأنماط والموضع",
    support: "الدعم",
    syncMatrix: "مزامنة المصفوفة",
    termsOfUse: "شروط الاستخدام",
    text: "نص",
    textColor: "لون النص",
    theSyndicate: "النقابة",
    theZenithCollection: "مجموعة زينيث",
    thin: "رفيع",
    tipUploadMoreImages: "نصيحة: يمكنك رفع المزيد من الصور في لوحة التحكم > الوسائط.",
    twitter: "تويتر",
    units: "وحدات",
    uploadFirstImage: "ارفع صورتك الأولى",
    url: "رابط",
    valuation: "التقييم",
    valuePlaceholder: "القيمة...",
    variants: "المتغيرات",
    vaultEmpty: "الخزنة فارغة",
    viewSeries: "عرض السلسلة",
    visualLink: "رابط مرئي",
    visualNode: "عقدة مرئية",
    whatAreYouLookingFor: "ماذا تبحث عنه؟"
  }
};

export type TranslationKey = keyof typeof translations.en;

interface LanguageState {
  language: 'en' | 'ar';
  setLanguage: (lang: 'en' | 'ar') => void;
  t: (key: TranslationKey) => string;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'en',
      setLanguage: (lang) => set({ language: lang }),
      t: (key: TranslationKey) => {
        const lang = get().language;
        return (translations[lang] as Record<string, string>)[key] || key;
      }
    }),
    {
      name: 'language-storage',
    }
  )
);
