import { create } from 'zustand';
import { persist } from 'zustand/middleware';

interface LanguageState {
  language: 'en' | 'ar';
  setLanguage: (lang: 'en' | 'ar') => void;
  t: (key: string) => string;
}

export const translations = {
  en: {
    home: "Home",
    shop: "Shop",
    shopAll: "Shop All",
    collections: "Collections",
    categories: "Categories",
    boutique: "Boutique",
    drop: "Drop",
    search: "Search...",
    myAccount: "My Account",
    adminPanel: "Admin Panel",
    signOut: "Sign Out",
    signIn: "Sign In",
    createAccount: "Create Account",
    
    // Storefront General
    addToCart: "Add to Cart",
    cart: "Cart",
    featuredProducts: "Featured Products",
    exploreCollections: "Explore Collections",
    saleOffers: "Sale Offers",
    testimonials: "Testimonials",
    videoSection: "Video",
    marquee: "Announcement",
    aboutUs: "About Us",
    reviews: "Reviews",

    // Admin Sidebar
    overview: "Overview",
    products: "Products",
    orders: "Orders",
    mediaHub: "Media Hub",
    banners: "Banners",
    storeBuilder: "Store Builder",
    siteBuilder: "Site Builder",
    generalSettings: "General Settings",
    siteSettings: "Site Settings",
    platformStores: "Platform Stores",
    templates: "Templates",
    toursPackages: "Tours & Packages",
    bookingInquiries: "Booking Inquiries",
    bannersSliders: "Banners & Sliders",
    mainControl: "Main Control",
    systemAdmin: "System Admin",
    customization: "Customization",

    // Admin settings tabs and headers
    general: "General",
    theme: "Colors & Style",
    header: "Header & Navigation",
    signature: "Advanced Features",
    tracking: "Pixels & Tracking",
    business: "Shipping & Delivery",
    storeCore: "Store Core",
    masterControl: "Master control for your brand identity and ecosystem.",
    brandMatrix: "Brand Matrix",
    marketIdentity: "Market Identity (Title)",
    enterStoreName: "Enter Store Name",
    seoSignal: "SEO Signal (Description)",
    premiumExperience: "Premium e-commerce experience...",
    signatureLogo: "Signature Logo (Header)",
    browserNode: "Browser Node (Favicon)",
    saveChanges: "Save Changes",
    saving: "Saving...",
    settingsSaved: "Settings saved successfully",
    themeConfiguration: "Theme Configuration",
    primaryColor: "Primary Accent Color",
    logoUpload: "Logo Upload",
    navigationMenu: "Navigation Menu",
    logisticsGrids: "Logistics Grids",
    defineGrid: "Define Grid",
    zoneIdentifier: "Zone Identifier",
    rateValue: "Rate Value",
    livePulse: "Live Pulse Notifications",
    pulseInterval: "Pulse Interval (Seconds)",
    socialProof: "Social Proof Matrix",
    injectReview: "Inject Review",
    identity: "Identity",
    coordinates: "Coordinates",
    reviewContent: "Review Content",

    // Comm Channels (General Settings)
    commChannels: "Comm Channels",
    uplinkEmail: "Uplink Email",
    voiceDirect: "Voice Direct",
    secureWhatsapp: "Secure WhatsApp",
    faviconSpec: "Global standard: 32x32px or 64x64px Resource.",

    // Header topology (Header tab)
    headerTopology: "Header Topology",
    navigationNodes: "Navigation Nodes",
    injectLink: "+ Inject Link",
    label: "Label",
    uplinkPath: "Uplink Path",
    
    // Header Layouts
    legacyLayout: "Legacy",
    legacyLayoutDesc: "Original structure parameters.",
    symmetricLayout: "Symmetric",
    symmetricLayoutDesc: "Logo Left, Balanced Central Matrix.",
    focusLayout: "Focus",
    focusLayoutDesc: "Links Left, Identity Center Node.",
    discreteLayout: "Discrete",
    discreteLayoutDesc: "Stealth Identity, Action Focused.",
    luxuryLayout: "High-End",
    luxuryLayoutDesc: "Vertical Stacked Premium Identity.",
    fluidLayout: "Fluid",
    fluidLayoutDesc: "Mobile-First Dynamic Interface.",

    // Color Architecture (Theme tab)
    colorArchitecture: "Color Architecture",
    colorArchitectureDesc: "Define the visual DNA of your storefront across all modules.",
    aestheticSynthesis: "Aesthetic Synthesis Engine",
    globalColorControl: "Global Color Injection & Matrix Control",
    versionActive: "V4.0 Active",
    phaseA: "Phase A (Primary)",
    phaseB: "Phase B (Secondary)",
    flowPattern: "Flow Pattern",
    linearVertical: "Linear (Vertical)",
    linearHorizontal: "Linear (Horizontal)",
    diagonalFlow: "Diagonal (Flow)",
    radialCore: "Radial (Core)",
    injectionNode: "Injection Node",
    globalFullMesh: "Global (Full Mesh)",
    nexusHome: "Nexus (Home)",
    baseFooter: "Base (Footer)",
    archiveShop: "Archive (Shop)",
    neuralCategories: "Neural (Categories)",
    signalProduct: "Signal (Product)",
    gatewayCart: "Gateway (Cart)",
    secureCheckout: "Secure (Checkout)",
    targetStream: "Target Stream",
    atmosphereBg: "Atmosphere (BG)",
    frequencyText: "Frequency (Text)",
    kineticMotion: "Kinetic Motion",
    static: "Static",
    animated: "Animated",
    applySynthesis: "Apply Synthesis",
    syncToCloud: "Sync to Cloud",
    homePageLabel: "Home Page",
    homePageDesc: "Main entry point and landing experience.",
    productGalleryLabel: "Product Gallery",
    productGalleryDesc: "Main shop and product listing grid.",
    collectionsLabel: "Collections",
    collectionsDesc: "Category browsing and discovery.",
    productDetailsLabel: "Product Details",
    productDetailsDesc: "Individual product showcase page.",
    shoppingCartLabel: "Shopping Cart",
    shoppingCartDesc: "Review and cart management layer.",
    checkoutPhaseLabel: "Checkout Phase",
    checkoutPhaseDesc: "Transaction and secure payment node.",
    globalSignalFooter: "Global Signal & Footer Matrix",
    primaryBrandIdentity: "Primary Brand Identity",
    footerAtmosphereBg: "Footer Atmosphere (BG)",
    footerSignalText: "Footer Signal (Text)",

    // Financial Signal
    financialSignalMatrix: "Financial Signal Matrix",
    priceDynamicsControl: "Price Dynamics & Sale Pulse Control",
    economyModule: "Economy Module",
    corePriceSignal: "Core Price Signal (Regular)",
    standardRateColor: "Standard Rate Color",
    pulseSignalSale: "Pulse Signal (Sale Price)",
    discountPulseColor: "Discount Pulse Color",

    // Tracking
    observatoryPixels: "Observatory Pixels",
    metaPixel: "Meta Pixel",
    tiktokSignal: "TikTok Signal",
    snapProtocol: "Snap Protocol",
    analyticsG4: "Analytics G4",
    secretId: "Secret ID",

    // Protocol messages
    protocolSecured: "Protocol Secured",
    uplinkPending: "Uplink Pending",

    // Dashboard
    websiteAnalytics: "Website Analytics",
    analyticsDashboard: "Analytics Dashboard",
    websiteAnalyticsDesc: "Comprehensive overview of your showcase website and booking inquiries.",
    analyticsDashboardDesc: "Comprehensive overview of your store's digital performance.",
    inquiryLeads: "Inquiry Leads",
    totalRevenue: "Total Revenue",
    uniqueLeads: "Unique Leads",
    responseRate: "Response Rate",
    vsLastMonth: "Vs Last Month",
    pageVisits: "Page Visits",
    totalOrders: "Total Orders",
    conversionRate: "Conversion",
    trafficSource: "Traffic Source",
    avgValue: "Avg Value",
    activePackages: "Active Packages",
    inStock: "In Stock",
    showcaseLive: "Showcase Live",
    needsAttention: "Needs Attention",
    tourismTemplate: "Tourism Template",
    activeProducts: "Active Products",
    leadsFunnel: "Leads Funnel",
    salesFunnel: "Sales Funnel",
    websiteVisits: "Website Visits",
    addToCartLabel: "Add to Cart",
    packageClicks: "Package Clicks",
    checkoutLabel: "Checkout",
    inquiriesSubmitted: "Inquiries Submitted",
    purchasedLabel: "Purchased",
    goalLabel: "Goal",
    popularPackages: "Popular Packages",
    bestSellers: "Best Sellers",
    inquiriesReceived: "Inquiries Received",
    unitsSold: "Units Sold",
    inquiryActivity: "Inquiry Activity",
    activityHeatmap: "Activity Heatmap",

    // Products / Assets
    inventoryVault: "Inventory Vault",
    controlProductPrecision: "Control your product ecosystem with precision.",
    addNewAsset: "Add New Asset",
    physicalAsset: "Physical Asset",
    servicePackage: "Service / Package",
    assetDesignation: "Asset Designation",
    assetNarrative: "Asset Narrative",
    baseValuation: "Base Valuation ($)",
    flashDiscount: "Flash Discount ($)",
    dimensionScale: "Dimension Scale",
    universalScale: "Universal Scale",
    colorSpectrum: "Color Spectrum",
    addSizePlaceholder: "Add size (e.g. XL, 42)...",
    add: "Add",
    confirmDeleteProduct: "Are you sure you want to delete this product?",

    // Banners
    motionCanvas: "Motion Canvas",
    curateVisualNarrative: "Curate your store's high-impact visual narrative.",
    sliderDynamics: "Slider Dynamics",
    globalTransitionProtocols: "Global behavior and transition protocols.",
    autoCycle: "Automatic Cycle",
    latencyMs: "Latency (MS)",
    morphEffect: "Morph Effect",
    uiControls: "UI Controls",
    tactileArrows: "Tactile Arrows",
    progressMap: "Progress Map",
    visualNodes: "Visual Nodes",
    frameInventory: "Frame Inventory",
    appendFrame: "Append Frame",
    noMediaProjected: "No Media Projected",
    initializeCinematicFrame: "Initialize your first cinematic frame to establish store presence.",
    launchSequence: "Launch Sequence",
    frame: "Frame",
    productionStatus: "Production Status",
    mainDistribution: "Main Distribution (16:9)",
    mobileNode: "Mobile Node (9:16)",
    manifestTitle: "Manifest Title",
    supportingNarrative: "Supporting Narrative",
    triggerText: "Trigger Text",
    deploymentUrl: "Deployment URL",
    renderActionUi: "Render Action UI",
    spatialPosition: "Spatial Position",
    visualArchitecture: "Visual Architecture",
    spatialContext: "Spatial Context",
    definePreciseGeographicalCoordinates: "Define the precise geographical coordinates of this frame within your storefront architecture.",
    commitToRegistry: "Commit to Registry",

    // Categories
    collectionHub: "Collection Hub",
    architectNavStructure: "Architect your store's navigational structure.",
    syncSuccessful: "Sync Successful",
    commitChanges: "Commit Changes",
    newCollection: "New Collection",
    visualMatrix: "Visual Matrix",
    defineStorefrontAesthetic: "Define your storefront aesthetic.",
    landingPage: "Landing Page",
    allCollections: "All Collections",
    modifySector: "Modify Sector",
    registerNewSector: "Register New Sector",
    sectorDesignation: "Sector Designation",
    narrativeDescription: "Narrative Description",
    structuralHierarchy: "Structural Hierarchy",
    visualSignature: "Visual Signature",
    collectionIdentity: "Collection Identity",
    registryCode: "Registry Code",
    operations: "Operations",
    confirmDeleteCategory: "Are you sure you want to delete this category?",

    // Orders
    orderStream: "Order Stream",
    realtimeTransactionMatrix: "Real-time transaction matrix and fulfillment control.",
    scanningMatrix: "Scanning Matrix...",
    activeRecords: "Active Records",
    noActiveTransactions: "No active transactions",
    node: "Node",
    revenue: "Revenue",
    matrixUnits: "Matrix Units",
    timeStamp: "Time Stamp",
    statusLabel: "Status",
    verified: "Verified",
    loadMoreOrders: "Load More Orders",
    syncingNextNode: "Syncing Next Node...",
    orderAnalysis: "Order Analysis",
    uplink: "Uplink",
    awaitingSelection: "Awaiting Selection",
    clickTransactionNode: "Click on a transaction node to initiate detailed analysis and fulfillment.",
    identityLogistics: "Identity & Logistics",
    subject: "Subject",
    deliveryCoordinates: "Delivery Coordinates",
    noCoordinatesProvided: "No coordinates provided",
    commChannel: "Comm Channel",
    productMatrix: "Product Matrix",
    customerIntelligence: "Customer Intelligence / Notes",
    accumulatedTotal: "Accumulated Total",
    protocolExecution: "Protocol Execution",

    // Colors
    advancedColorControls: "Advanced Color Controls",
    controlColorAspect: "Control every single color aspect for each specific template.",
    primaryAccentColor: "Primary Accent Color",
    mainBackground: "Main Background",
    mainTextColor: "Main Text Color",
    headerBackgroundLabel: "Header Background",
    headerTextLabel: "Header Text",
    footerBackgroundLabel: "Footer Background",
    footerTextLabel: "Footer Text",
    primaryButtonBackground: "Primary Button Background",
    primaryButtonText: "Primary Button Text",
    priceTextColor: "Price Text Color",
    salePriceColorLabel: "Sale Price Color",
    saveColors: "Save Colors",
    colorsSavedSuccessfully: "Colors saved successfully!",
    failedToSaveColors: "Failed to save colors. Please try again.",

    // Media
    assetVault: "Asset Vault",
    centralizedRepository: "Centralized repository for your store's visual resources.",
    items: "Items",
    activeResourceInventory: "Active Resource Inventory",
    newDeployment: "New Deployment",
    initializeAsset: "Initialize Asset",
    registerNewResource: "Register new resource to the vault",
    sourceProtocolUrl: "Source Protocol (URL)",
    directLinkExternal: "Direct link from external distribution node.",
    abort: "Abort",
    deployAsset: "Deploy Asset",
    nullOutput: "Null Output",
    confirmDeleteAsset: "Are you sure you want to delete this asset?",
    zeroAssetsDetected: "Zero Assets Detected",
    vaultCurrentlyEmpty: "Vault is currently empty. Initialize a new resource deployment to begin building your visual library.",
    startDeploymentSequence: "Start Deployment Sequence",

    // Templates
    storeTemplates: "Store Templates",
    selectLookFeel: "Select the look and feel of your storefront.",
    superAdminMode: "Super Admin Mode",
    hiddenFromUsers: "Hidden from Users",
    activeBadge: "ACTIVE",
    applyTemplate: "Apply Template",
    templateId: "Template ID:",
    confirmDeleteTemplate: "Are you sure you want to delete this template forever? This action cannot be undone."
  },
  ar: {
    home: "الرئيسية",
    shop: "المتجر",
    shopAll: "تسوق الكل",
    myAccount: "حسابي",
    adminPanel: "لوحة التحكم",
    signOut: "تسجيل الخروج",
    signIn: "تسجيل الدخول",
    createAccount: "إنشاء حساب",
    
    // Storefront General
    addToCart: "إضافة للسلة",
    cart: "السلة",
    featuredProducts: "منتجات مميزة",
    exploreCollections: "استكشف المجموعات",
    saleOffers: "عروض التخفيضات",
    testimonials: "آراء العملاء",
    videoSection: "فيديو",
    marquee: "شريط الإعلانات",
    aboutUs: "من نحن",
    reviews: "التقييمات",

    // Admin Sidebar
    overview: "الرئيسية",
    products: "المنتجات",
    orders: "الطلبات",
    mediaHub: "مكتبة الوسائط",
    banners: "البانرات",
    storeBuilder: "مطور المتجر",
    siteBuilder: "مطور الموقع",
    generalSettings: "الإعدادات العامة",
    siteSettings: "إعدادات الموقع",
    platformStores: "متاجر المنصة",
    templates: "القوالب",
    toursPackages: "البرامج السياحية",
    bookingInquiries: "استفسارات الحجز",
    bannersSliders: "البانرات والشرائح",
    mainControl: "التحكم الرئيسي",
    systemAdmin: "إدارة النظام",
    customization: "التخصيص",

    // Admin settings tabs and headers
    general: "عام",
    theme: "الألوان والمظهر",
    header: "رأس الصفحة والتنقل",
    signature: "ميزات متقدمة",
    tracking: "أكواد التتبع والبيكسل",
    business: "الشحن والتوصيل",
    storeCore: "نواة المتجر",
    masterControl: "التحكم الكامل في الهوية البصرية وشعار العلامة التجارية.",
    brandMatrix: "مصفوفة العلامة التجارية",
    marketIdentity: "اسم المتجر (العنوان)",
    enterStoreName: "أدخل اسم المتجر",
    seoSignal: "وصف المتجر (SEO)",
    premiumExperience: "تجربة تسوق فريدة ومميزة...",
    signatureLogo: "شعار الهيدر الرئيسي",
    browserNode: "أيقونة المتصفح (Favicon)",
    saveChanges: "حفظ التغييرات",
    saving: "جاري الحفظ...",
    settingsSaved: "تم حفظ الإعدادات بنجاح",
    themeConfiguration: "تهيئة المظهر واللون",
    primaryColor: "اللون الأساسي المميز",
    logoUpload: "رفع الشعار",
    navigationMenu: "قائمة التصفح الرئيسية",
    logisticsGrids: "خيارات وتكلفة الشحن",
    defineGrid: "تحديد المنطقة",
    zoneIdentifier: "معرف منطقة الشحن",
    rateValue: "قيمة التكلفة",
    livePulse: "تنبيهات حية للمبيعات",
    pulseInterval: "معدل التكرار (بالثواني)",
    socialProof: "آراء وتقييمات العملاء",
    injectReview: "إضافة تقييم جديد",
    identity: "اسم العميل",
    coordinates: "البلد أو المدينة",
    reviewContent: "محتوى التقييم",

    // Comm Channels (General Settings)
    commChannels: "قنوات التواصل",
    uplinkEmail: "بريد التواصل",
    voiceDirect: "رقم الهاتف المباشر",
    secureWhatsapp: "رقم الواتساب الفعال",
    faviconSpec: "المقاس القياسي المقترح: 32x32 أو 64x64 بكسل.",

    // Header topology (Header tab)
    headerTopology: "تنسيق الهيدر العلوي",
    navigationNodes: "روابط قائمة التنقل",
    injectLink: "+ إضافة رابط جديد",
    label: "اسم الرابط",
    uplinkPath: "مسار الرابط (الرابط)",
    
    // Header Layouts
    legacyLayout: "التقليدي",
    legacyLayoutDesc: "التنسيق الكلاسيكي القديم لمتجرك.",
    symmetricLayout: "المتوازن",
    symmetricLayoutDesc: "الشعار في اليسار، وروابط التنقل في المنتصف.",
    focusLayout: "المركّز",
    focusLayoutDesc: "الروابط في اليسار، الشعار في المنتصف.",
    discreteLayout: "المبسط",
    discreteLayoutDesc: "مظهر بسيط يركز على إجراءات العميل.",
    luxuryLayout: "الفاخر",
    luxuryLayoutDesc: "تصميم متدرج فاخر لعلامتك التجارية.",
    fluidLayout: "الديناميكي",
    fluidLayoutDesc: "تنسيق متجاوب بالكامل مخصص للهواتف أولاً.",

    // Color Architecture (Theme tab)
    colorArchitecture: "هندسة الألوان",
    colorArchitectureDesc: "حدد هوية الألوان الخاصة بمتجرك لجميع الصفحات والمكونات.",
    aestheticSynthesis: "محرك دمج الألوان",
    globalColorControl: "التحكم الكامل بألوان المتجر والمظهر البصري",
    versionActive: "النسخة الرابعة نشطة",
    phaseA: "اللون الأساسي",
    phaseB: "اللون الثانوي",
    flowPattern: "نمط تدرج الألوان",
    linearVertical: "خطي (عمودي)",
    linearHorizontal: "خطي (أفقي)",
    diagonalFlow: "تدرج قطري",
    radialCore: "شعاعي مركزي",
    injectionNode: "مكان تطبيق التدرج",
    globalFullMesh: "كامل الموقع",
    nexusHome: "الصفحة الرئيسية فقط",
    baseFooter: "تذييل الصفحة (الفوتر)",
    archiveShop: "صفحة المنتجات",
    neuralCategories: "صفحة الفئات",
    signalProduct: "تفاصيل المنتج",
    gatewayCart: "سلة المشتريات",
    secureCheckout: "صفحة الدفع الآمن",
    targetStream: "العنصر المستهدف",
    atmosphereBg: "خلفية الصفحة",
    frequencyText: "لون النصوص الرئيسي",
    kineticMotion: "الحركة والتأثيرات",
    static: "ثابت",
    animated: "متحرك وتفاعلي",
    applySynthesis: "تطبيق التنسيق والألوان",
    syncToCloud: "مزامنة البيانات سحابياً",
    homePageLabel: "الصفحة الرئيسية",
    homePageDesc: "الواجهة الأساسية والإنطباع الأول للعميل.",
    productGalleryLabel: "معرض المنتجات",
    collectionsDesc: "تصفح الأقسام واكتشاف المنتجات.",
    productDetailsLabel: "تفاصيل المنتج",
    productDetailsDesc: "صفحة عرض وتفاصيل المنتج الفردي.",
    shoppingCartLabel: "سلة التسوق",
    shoppingCartDesc: "مراجعة وإدارة السلة.",
    checkoutPhaseLabel: "مرحلة الدفع",
    checkoutPhaseDesc: "إتمام المعاملة والدفع الآمن.",
    globalSignalFooter: "التحكم الشامل وتذييل الصفحة",
    primaryBrandIdentity: "اللون الأساسي للعلامة التجارية",
    footerAtmosphereBg: "خلفية تذييل الصفحة",
    footerSignalText: "نص تذييل الصفحة",

    // Financial Signal
    financialSignalMatrix: "مصفوفة التحكم المالي والأسعار",
    priceDynamicsControl: "ديناميكيات الأسعار والتحكم بالعروض",
    economyModule: "وحدة الاقتصاد والمالية",
    corePriceSignal: "السعر الأساسي (الافتراضي)",
    standardRateColor: "لون السعر القياسي",
    pulseSignalSale: "السعر المخفض (العرض)",
    discountPulseColor: "لون سعر الخصم",

    // Tracking
    observatoryPixels: "وحدات بكسل التتبع والتحليل",
    metaPixel: "بكسل ميتا (فيسبوك)",
    tiktokSignal: "إشارات تيك توك",
    snapProtocol: "سناب شات",
    analyticsG4: "تحليلات جوجل (GA4)",
    secretId: "معرف بكسل التتبع (ID)",

    // Protocol messages
    protocolSecured: "تم حفظ الإعدادات بنجاح",
    uplinkPending: "بانتظار الحفظ والرفع",

    // Dashboard
    websiteAnalytics: "تحليلات الموقع",
    analyticsDashboard: "لوحة التحليلات",
    websiteAnalyticsDesc: "نظرة شاملة على موقعك الاستعراضي واستفسارات الحجز.",
    analyticsDashboardDesc: "نظرة شاملة على الأداء الرقمي لمتجرك.",
    inquiryLeads: "الاستفسارات المحتملة",
    totalRevenue: "إجمالي الإيرادات",
    uniqueLeads: "زوار فريدون",
    responseRate: "معدل الاستجابة",
    vsLastMonth: "مقارنة بالشهر الماضي",
    pageVisits: "زيارات الصفحة",
    totalOrders: "إجمالي الطلبات",
    conversionRate: "معدل التحويل",
    trafficSource: "مصدر الزيارات",
    avgValue: "متوسط القيمة",
    activePackages: "الباقات النشطة",
    inStock: "متوفر في المخزن",
    showcaseLive: "العرض المباشر",
    needsAttention: "يحتاج للاهتمام",
    tourismTemplate: "قالب السياحة",
    activeProducts: "المنتجات النشطة",
    leadsFunnel: "قمع الاستفسارات",
    salesFunnel: "المبيعات",
    websiteVisits: "زيارات الموقع",
    addToCartLabel: "إضافة للسلة",
    packageClicks: "نقرات الباقات",
    checkoutLabel: "الدفع",
    inquiriesSubmitted: "الاستفسارات المقدمة",
    purchasedLabel: "المشتريات",
    goalLabel: "الهدف",
    popularPackages: "الباقات الشائعة",
    bestSellers: "الأكثر مبيعاً",
    inquiriesReceived: "الاستفسارات المستلمة",
    unitsSold: "الوحدات المباعة",
    inquiryActivity: "نشاط الاستفسارات",
    activityHeatmap: "خريطة النشاط",

    // Products / Assets
    inventoryVault: "المخزون",
    controlProductPrecision: "تحكم في نظام المنتجات الخاص بك بدقة.",
    addNewAsset: "إضافة منتج جديد",
    physicalAsset: "أصل مادي",
    servicePackage: "خدمة / باقة",
    assetDesignation: "تسمية الأصل",
    assetNarrative: "وصف الأصل",
    baseValuation: "التقييم الأساسي ($)",
    flashDiscount: "خصم فوري ($)",
    dimensionScale: "مقياس الأبعاد",
    universalScale: "المقياس العالمي",
    colorSpectrum: "طيف الألوان",
    addSizePlaceholder: "إضافة حجم (مثال XL, 42)...",
    add: "إضافة",
    confirmDeleteProduct: "هل أنت متأكد من حذف هذا المنتج؟",

    // Banners
    motionCanvas: "لوحة الحركة",
    curateVisualNarrative: "نظم القصة البصرية المؤثرة لمتجرك.",
    sliderDynamics: "ديناميكيات الشريط المتحرك",
    globalTransitionProtocols: "السلوك العام وبروتوكولات الانتقال.",
    autoCycle: "دورة تلقائية",
    latencyMs: "الكمون (ملي ثانية)",
    morphEffect: "تأثير التحول",
    uiControls: "عناصر تحكم واجهة المستخدم",
    tactileArrows: "أسهم ملموسة",
    progressMap: "خريطة التقدم",
    visualNodes: "العقد البصرية",
    frameInventory: "مخزون الإطارات",
    appendFrame: "إضافة إطار",
    noMediaProjected: "لا يوجد وسائط معروضة",
    initializeCinematicFrame: "قم بتهيئة إطارك السينمائي الأول لإنشاء حضور متجرك.",
    launchSequence: "تسلسل الإطلاق",
    frame: "إطار",
    productionStatus: "حالة الإنتاج",
    mainDistribution: "التوزيع الرئيسي (16:9)",
    mobileNode: "عقدة الموبايل (9:16)",
    manifestTitle: "عنوان البيان",
    supportingNarrative: "نص مساعد",
    triggerText: "نص الزر",
    deploymentUrl: "رابط النشر",
    renderActionUi: "عرض واجهة الحدث",
    spatialPosition: "الموضع المكاني",
    visualArchitecture: "البنية المرئية",
    spatialContext: "السياق المكاني",
    definePreciseGeographicalCoordinates: "تحديد الإحداثيات الجغرافية الدقيقة لهذا الإطار ضمن متجرك.",
    commitToRegistry: "حفظ السجل",

    // Categories
    collectionHub: "مركز المجموعات",
    architectNavStructure: "صمم الهيكل الملاحي لمتجرك.",
    syncSuccessful: "تمت المزامنة بنجاح",
    commitChanges: "حفظ التغييرات",
    newCollection: "مجموعة جديدة",
    visualMatrix: "المصفوفة المرئية",
    defineStorefrontAesthetic: "حدد جمالية واجهة متجرك.",
    landingPage: "الصفحة المقصودة",
    allCollections: "كل المجموعات",
    modifySector: "تعديل القطاع",
    registerNewSector: "تسجيل قطاع جديد",
    sectorDesignation: "تسمية القطاع",
    narrativeDescription: "الوصف السردي",
    structuralHierarchy: "التسلسل الهرمي الهيكلي",
    visualSignature: "التوقيع البصري",
    collectionIdentity: "هوية المجموعة",
    registryCode: "رمز السجل",
    operations: "العمليات",
    confirmDeleteCategory: "هل أنت متأكد من حذف هذا القسم؟",

    // Orders
    orderStream: "الطلبات",
    realtimeTransactionMatrix: "مصفوفة المعاملات في الوقت الفعلي والتحكم في التنفيذ.",
    scanningMatrix: "جاري فحص المصفوفة...",
    activeRecords: "سجلات نشطة",
    noActiveTransactions: "لا توجد معاملات نشطة",
    node: "العقدة",
    revenue: "الإيرادات",
    matrixUnits: "العدد",
    timeStamp: "الطابع الزمني",
    statusLabel: "الحالة",
    verified: "مؤكد",
    loadMoreOrders: "تحميل المزيد من الطلبات",
    syncingNextNode: "جاري مزامنة العقدة التالية...",
    orderAnalysis: "تحليل الطلب",
    uplink: "الرابط الصاعد",
    awaitingSelection: "في انتظار الاختيار",
    clickTransactionNode: "انقر فوق عقدة معاملة لبدء التحليل والتنفيذ المفصل.",
    identityLogistics: "الهوية واللوجستيات",
    subject: "الموضوع",
    deliveryCoordinates: "إحداثيات التسليم",
    noCoordinatesProvided: "لم يتم توفير إحداثيات",
    commChannel: "قناة التواصل",
    productMatrix: "مصفوفة المنتجات",
    customerIntelligence: "ملاحظات / استخبارات العملاء",
    accumulatedTotal: "الإجمالي المتراكم",
    protocolExecution: "تنفيذ البروتوكول",

    // Colors
    advancedColorControls: "عناصر تحكم متقدمة بالألوان",
    controlColorAspect: "تحكم في كل جانب من جوانب الألوان لكل قالب.",
    primaryAccentColor: "اللون المميز الأساسي",
    mainBackground: "الخلفية الرئيسية",
    mainTextColor: "لون النص الرئيسي",
    headerBackgroundLabel: "خلفية الترويسة",
    headerTextLabel: "نص الترويسة",
    footerBackgroundLabel: "خلفية التذييل",
    footerTextLabel: "نص التذييل",
    primaryButtonBackground: "خلفية الزر الرئيسي",
    primaryButtonText: "نص الزر الرئيسي",
    priceTextColor: "لون نص السعر",
    salePriceColorLabel: "لون سعر التخفيض",
    saveColors: "حفظ الألوان",
    colorsSavedSuccessfully: "تم حفظ الألوان بنجاح!",
    failedToSaveColors: "فشل حفظ الألوان. يرجى المحاولة مرة أخرى.",

    // Media
    assetVault: "خزينة الأصول",
    centralizedRepository: "مستودع مركزي للموارد المرئية لمتجرك.",
    items: "عناصر",
    activeResourceInventory: "مخزون الموارد النشطة",
    newDeployment: "نشر جديد",
    initializeAsset: "تهيئة أصل",
    registerNewResource: "تسجيل مورد جديد في الخزينة",
    sourceProtocolUrl: "بروتوكول المصدر (رابط)",
    directLinkExternal: "رابط مباشر من عقدة توزيع خارجية.",
    abort: "إلغاء",
    deployAsset: "نشر الأصل",
    nullOutput: "لا يوجد مخرجات",
    confirmDeleteAsset: "هل أنت متأكد من حذف هذا الأصل؟",
    zeroAssetsDetected: "تم اكتشاف صفر أصول",
    vaultCurrentlyEmpty: "الخزينة فارغة حالياً. قم بتهيئة نشر مورد جديد لبدء بناء مكتبتك المرئية.",
    startDeploymentSequence: "بدء تسلسل النشر",

    // Templates
    storeTemplates: "قوالب المتجر",
    selectLookFeel: "حدد شكل ومظهر متجرك.",
    superAdminMode: "وضع المدير المتميز",
    hiddenFromUsers: "مخفي عن المستخدمين",
    activeBadge: "نشط",
    applyTemplate: "تطبيق القالب",
    templateId: "معرف القالب:",
    confirmDeleteTemplate: "هل أنت متأكد من حذف هذا القالب نهائياً؟ لا يمكن التراجع."
  }
};

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'en',
      setLanguage: (lang) => set({ language: lang }),
      t: (key: string) => {
        const lang = get().language;
        // @ts-ignore
        return translations[lang][key] || key;
      }
    }),
    {
      name: 'language-storage',
    }
  )
);
